


	
	
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//		Template file LINQGenerationTemplate.xml
//		Vault version 30
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Thinkage.MainBoss.WebAccess.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;

	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Master")]
	public partial class AssignmentDataContext : System.Data.Linq.DataContext
	{
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion

		public AssignmentDataContext() :
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Master"].ConnectionString, mappingSource)
		{
			OnCreated();
		}

		public AssignmentDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public AssignmentDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public AssignmentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public AssignmentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrder> WorkOrder
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrder>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrderState> WorkOrderState
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrderState>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrderStateHistory> WorkOrderStateHistory
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrderStateHistory>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrder> PurchaseOrder
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrder>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrderState> PurchaseOrderState
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrderState>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrderStateHistory> PurchaseOrderStateHistory
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrderStateHistory>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.RequestState> RequestState
		{
			get
			{
				return this.GetTable<AssignmentEntities.RequestState>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.RequestStateHistory> RequestStateHistory
		{
			get
			{
				return this.GetTable<AssignmentEntities.RequestStateHistory>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrderAssignee> WorkOrderAssignee
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrderAssignee>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.AttentionStatus> AttentionStatus
		{
			get
			{
				return this.GetTable<AssignmentEntities.AttentionStatus>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.User> User
		{
			get
			{
				return this.GetTable<AssignmentEntities.User>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.Contact> Contact
		{
			get
			{
				return this.GetTable<AssignmentEntities.Contact>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.RequestAssignee> RequestAssignee
		{
			get
			{
				return this.GetTable<AssignmentEntities.RequestAssignee>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.RequestAssigneeStatistics> RequestAssigneeStatistics
		{
			get
			{
				return this.GetTable<AssignmentEntities.RequestAssigneeStatistics>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrderAssigneeStatistics> WorkOrderAssigneeStatistics
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrderAssigneeStatistics>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrderAssignee> PurchaseOrderAssignee
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrderAssignee>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrderAssigneeStatistics> PurchaseOrderAssigneeStatistics
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrderAssigneeStatistics>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.DatabaseStatus> DatabaseStatus
		{
			get
			{
				return this.GetTable<AssignmentEntities.DatabaseStatus>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.Request> Request
		{
			get
			{
				return this.GetTable<AssignmentEntities.Request>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.RequestAssignment> RequestAssignment
		{
			get
			{
				return this.GetTable<AssignmentEntities.RequestAssignment>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.WorkOrderAssignmentAll> WorkOrderAssignmentAll
		{
			get
			{
				return this.GetTable<AssignmentEntities.WorkOrderAssignmentAll>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PurchaseOrderAssignment> PurchaseOrderAssignment
		{
			get
			{
				return this.GetTable<AssignmentEntities.PurchaseOrderAssignment>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.PMGenerationBatch> PMGenerationBatch
		{
			get
			{
				return this.GetTable<AssignmentEntities.PMGenerationBatch>();
			}
		}
		public System.Data.Linq.Table<AssignmentEntities.BackupFileName> BackupFileName
		{
			get
			{
				return this.GetTable<AssignmentEntities.BackupFileName>();
			}
		}
  
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_vgetDBVersion]", IsComposable=true)]
		public string _vgetDBVersion()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
	}
}
namespace AssignmentEntities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	using System.Runtime.CompilerServices;
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrder")]
	public partial class WorkOrder
	{
		// Denotes table WorkOrder with labelkey='Work Order'
		static public string WorkOrderLabelKey { get{return AssignmentLabelKdsMBLabel.K("Work Order").Translate();}}
		private System.Guid _Id;

		public WorkOrder()
		{
		}
		/// Denotes the WorkOrder's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrder_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrder),Name="WorkOrder_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrderState")]
	public partial class WorkOrderState
	{
		// Denotes table WorkOrderState with labelkey='Work Order State'
		static public string WorkOrderStateLabelKey { get{return AssignmentLabelKdsMBLabel.K("Work Order State").Translate();}}
		private System.Guid _Id;

		public WorkOrderState()
		{
		}
		/// Denotes the WorkOrderState's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrderState_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrderState),Name="WorkOrderState_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrderStateHistory")]
	public partial class WorkOrderStateHistory
	{
		// Denotes table WorkOrderStateHistory with labelkey='Work Order State History'
		static public string WorkOrderStateHistoryLabelKey { get{return AssignmentLabelKdsMBLabel.K("Work Order State History").Translate();}}
		private System.Guid _Id;

		public WorkOrderStateHistory()
		{
		}
		/// Denotes the WorkOrderStateHistory's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrderStateHistory_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrderStateHistory),Name="WorkOrderStateHistory_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrder")]
	public partial class PurchaseOrder
	{
		// Denotes table PurchaseOrder with labelkey='Purchase Order'
		static public string PurchaseOrderLabelKey { get{return AssignmentLabelKdsMBLabel.K("Purchase Order").Translate();}}
		private System.Guid _Id;

		public PurchaseOrder()
		{
		}
		/// Denotes the PurchaseOrder's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrder_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrder),Name="PurchaseOrder_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrderState")]
	public partial class PurchaseOrderState
	{
		// Denotes table PurchaseOrderState with labelkey='Purchase Order State'
		static public string PurchaseOrderStateLabelKey { get{return AssignmentLabelKdsMBLabel.K("Purchase Order State").Translate();}}
		private System.Guid _Id;

		public PurchaseOrderState()
		{
		}
		/// Denotes the PurchaseOrderState's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrderState_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrderState),Name="PurchaseOrderState_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrderStateHistory")]
	public partial class PurchaseOrderStateHistory
	{
		// Denotes table PurchaseOrderStateHistory with labelkey='Purchase Order State History'
		static public string PurchaseOrderStateHistoryLabelKey { get{return AssignmentLabelKdsMBLabel.K("Purchase Order State History").Translate();}}
		private System.Guid _Id;

		public PurchaseOrderStateHistory()
		{
		}
		/// Denotes the PurchaseOrderStateHistory's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrderStateHistory_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrderStateHistory),Name="PurchaseOrderStateHistory_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequestState")]
	public partial class RequestState
	{
		// Denotes table RequestState with labelkey='Request State'
		static public string RequestStateLabelKey { get{return AssignmentLabelKdsMBLabel.K("Request State").Translate();}}
		private System.Guid _Id;

		public RequestState()
		{
		}
		/// Denotes the RequestState's Id column with type id(nonnull) with labelkey='Id'
		static public string RequestState_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.RequestState),Name="RequestState_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequestStateHistory")]
	public partial class RequestStateHistory
	{
		// Denotes table RequestStateHistory with labelkey='Request State History'
		static public string RequestStateHistoryLabelKey { get{return AssignmentLabelKdsMBLabel.K("Request State History").Translate();}}
		private System.Guid _Id;

		public RequestStateHistory()
		{
		}
		/// Denotes the RequestStateHistory's Id column with type id(nonnull) with labelkey='Id'
		static public string RequestStateHistory_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.RequestStateHistory),Name="RequestStateHistory_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrderAssignee")]
	public partial class WorkOrderAssignee
	{
		// Denotes table WorkOrderAssignee with labelkey='Work Order Assignee'
		static public string WorkOrderAssigneeLabelKey { get{return AssignmentLabelKdsMBLabel.K("Work Order Assignee").Translate();}}
		private System.Guid _Id;

		public WorkOrderAssignee()
		{
		}
		/// Denotes the WorkOrderAssignee's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrderAssignee_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrderAssignee),Name="WorkOrderAssignee_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AttentionStatus")]
	public partial class AttentionStatus
	{
		// Denotes table AttentionStatus with labelkey=''
		static public string AttentionStatusLabelKey { get{return AssignmentLabelKdsMBLabel.K("").Translate();}}
		private System.Guid _Id;
		private System.Guid _UserID;
		private int? _NumNewRequests;
		private int? _NumInProgressRequests;
		private int? _NumNewWorkOrders;
		private int? _NumInProgressWorkOrders;
		private int? _NumNewPurchaseOrders;
		private int? _NumInProgressPurchaseOrders;
		private EntityRef<User> _User;

		public AttentionStatus()
		{
			this._User = default(EntityRef<User>);
		}
		/// Denotes the AttentionStatus's Id column with type id(nonnull) with labelkey='Id'
		static public string AttentionStatus_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		/// Denotes the AttentionStatus's UserID column with type link(nonnull, field User.Id) with labelkey='User'
		static public string AttentionStatus_UserID{ get{return AssignmentLabelKdsMBLabel.K("User").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_UserID")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UNIQUEIDENTIFIER", CanBeNull=false)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumNewRequests column with type integer(32) with labelkey='NumNewRequests'
		static public string AttentionStatus_NumNewRequests{ get{return AssignmentLabelKdsMBLabel.K("NumNewRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumNewRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumNewRequests", DbType="INT")]
		public int? NumNewRequests
		{
			get
			{
				return this._NumNewRequests;
			}
			set
			{
				if ((this._NumNewRequests != value))
				{
					this._NumNewRequests = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumInProgressRequests column with type integer(32) with labelkey='NumInProgressRequests'
		static public string AttentionStatus_NumInProgressRequests{ get{return AssignmentLabelKdsMBLabel.K("NumInProgressRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumInProgressRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumInProgressRequests", DbType="INT")]
		public int? NumInProgressRequests
		{
			get
			{
				return this._NumInProgressRequests;
			}
			set
			{
				if ((this._NumInProgressRequests != value))
				{
					this._NumInProgressRequests = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumNewWorkOrders column with type integer(32) with labelkey='NumNewWorkOrders'
		static public string AttentionStatus_NumNewWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumNewWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumNewWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumNewWorkOrders", DbType="INT")]
		public int? NumNewWorkOrders
		{
			get
			{
				return this._NumNewWorkOrders;
			}
			set
			{
				if ((this._NumNewWorkOrders != value))
				{
					this._NumNewWorkOrders = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumInProgressWorkOrders column with type integer(32) with labelkey='NumInProgressWorkOrders'
		static public string AttentionStatus_NumInProgressWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumInProgressWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumInProgressWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumInProgressWorkOrders", DbType="INT")]
		public int? NumInProgressWorkOrders
		{
			get
			{
				return this._NumInProgressWorkOrders;
			}
			set
			{
				if ((this._NumInProgressWorkOrders != value))
				{
					this._NumInProgressWorkOrders = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumNewPurchaseOrders column with type integer(32) with labelkey='NumNewPurchaseOrders'
		static public string AttentionStatus_NumNewPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumNewPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumNewPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumNewPurchaseOrders", DbType="INT")]
		public int? NumNewPurchaseOrders
		{
			get
			{
				return this._NumNewPurchaseOrders;
			}
			set
			{
				if ((this._NumNewPurchaseOrders != value))
				{
					this._NumNewPurchaseOrders = value;
				}
			}
		}
		/// Denotes the AttentionStatus's NumInProgressPurchaseOrders column with type integer(32) with labelkey='NumInProgressPurchaseOrders'
		static public string AttentionStatus_NumInProgressPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumInProgressPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.AttentionStatus),Name="AttentionStatus_NumInProgressPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumInProgressPurchaseOrders", DbType="INT")]
		public int? NumInProgressPurchaseOrders
		{
			get
			{
				return this._NumInProgressPurchaseOrders;
			}
			set
			{
				if ((this._NumInProgressPurchaseOrders != value))
				{
					this._NumInProgressPurchaseOrders = value;
				}
			}
		}
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_AttentionStatus", Storage="_User", ThisKey="UserID", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User")]
	public partial class User
	{
		// Denotes table User with labelkey='User'
		static public string UserLabelKey { get{return AssignmentLabelKdsMBLabel.K("User").Translate();}}
		private System.Guid _Id;
		private EntitySet<AttentionStatus> _AttentionStatusUser;

		public User()
		{
			this._AttentionStatusUser = new EntitySet<AttentionStatus>(new Action<AttentionStatus>(this.attach_AttentionStatusUser), new Action<AttentionStatus>(this.detach_AttentionStatusUser));
		}
		/// Denotes the User's Id column with type id(nonnull) with labelkey='Id'
		static public string User_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.User),Name="User_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_AttentionStatus", Storage="_AttentionStatusUser", ThisKey="Id", OtherKey="UserID")]
		public EntitySet<AttentionStatus> AttentionStatusUser
		{
			get
			{
				return this._AttentionStatusUser;
			}
			set
			{
				this._AttentionStatusUser.Assign(value);
			}
		}

		private void attach_AttentionStatusUser(AttentionStatus entity)
		{
			entity.User = this;
		}
		private void detach_AttentionStatusUser(AttentionStatus entity)
		{
			entity.User = null;
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
	public partial class Contact
	{
		// Denotes table Contact with labelkey='Contact'
		static public string ContactLabelKey { get{return AssignmentLabelKdsMBLabel.K("Contact").Translate();}}
		private System.Guid _Id;

		public Contact()
		{
		}
		/// Denotes the Contact's Id column with type id(nonnull) with labelkey='Id'
		static public string Contact_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.Contact),Name="Contact_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequestAssignee")]
	public partial class RequestAssignee
	{
		// Denotes table RequestAssignee with labelkey='RequestAssignee'
		static public string RequestAssigneeLabelKey { get{return AssignmentLabelKdsMBLabel.K("RequestAssignee").Translate();}}
		private System.Guid _Id;

		public RequestAssignee()
		{
		}
		/// Denotes the RequestAssignee's Id column with type id(nonnull) with labelkey='Id'
		static public string RequestAssignee_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.RequestAssignee),Name="RequestAssignee_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequestAssigneeStatistics")]
	public partial class RequestAssigneeStatistics
	{
		// Denotes table RequestAssigneeStatistics with labelkey='RequestAssigneeStatistics'
		static public string RequestAssigneeStatisticsLabelKey { get{return AssignmentLabelKdsMBLabel.K("RequestAssigneeStatistics").Translate();}}
		private System.Guid _Id;

		public RequestAssigneeStatistics()
		{
		}
		/// Denotes the RequestAssigneeStatistics's Id column with type id(nonnull) with labelkey='Id'
		static public string RequestAssigneeStatistics_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.RequestAssigneeStatistics),Name="RequestAssigneeStatistics_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrderAssigneeStatistics")]
	public partial class WorkOrderAssigneeStatistics
	{
		// Denotes table WorkOrderAssigneeStatistics with labelkey='WorkOrderAssigneeStatistics'
		static public string WorkOrderAssigneeStatisticsLabelKey { get{return AssignmentLabelKdsMBLabel.K("WorkOrderAssigneeStatistics").Translate();}}
		private System.Guid _Id;

		public WorkOrderAssigneeStatistics()
		{
		}
		/// Denotes the WorkOrderAssigneeStatistics's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrderAssigneeStatistics_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrderAssigneeStatistics),Name="WorkOrderAssigneeStatistics_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrderAssignee")]
	public partial class PurchaseOrderAssignee
	{
		// Denotes table PurchaseOrderAssignee with labelkey='PurchaseOrderAssignee'
		static public string PurchaseOrderAssigneeLabelKey { get{return AssignmentLabelKdsMBLabel.K("PurchaseOrderAssignee").Translate();}}
		private System.Guid _Id;

		public PurchaseOrderAssignee()
		{
		}
		/// Denotes the PurchaseOrderAssignee's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrderAssignee_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrderAssignee),Name="PurchaseOrderAssignee_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrderAssigneeStatistics")]
	public partial class PurchaseOrderAssigneeStatistics
	{
		// Denotes table PurchaseOrderAssigneeStatistics with labelkey='PurchaseOrderAssigneeStatistics'
		static public string PurchaseOrderAssigneeStatisticsLabelKey { get{return AssignmentLabelKdsMBLabel.K("PurchaseOrderAssigneeStatistics").Translate();}}
		private System.Guid _Id;

		public PurchaseOrderAssigneeStatistics()
		{
		}
		/// Denotes the PurchaseOrderAssigneeStatistics's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrderAssigneeStatistics_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrderAssigneeStatistics),Name="PurchaseOrderAssigneeStatistics_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatabaseStatus")]
	public partial class DatabaseStatus
	{
		// Denotes table DatabaseStatus with labelkey=''
		static public string DatabaseStatusLabelKey { get{return AssignmentLabelKdsMBLabel.K("").Translate();}}
		private System.Guid _Id;
		private int? _NumNewRequests;
		private int? _NumInProgressRequests;
		private int? _NumUnAssignedNewRequests;
		private int? _NumUnAssignedInProgressRequests;
		private int? _NumNewWorkOrders;
		private int? _NumOpenWorkOrders;
		private int? _NumUnAssignedNewWorkOrders;
		private int? _NumUnAssignedOpenWorkOrders;
		private int? _NumDraftPurchaseOrders;
		private int? _NumIssuedPurchaseOrders;
		private int? _NumUnAssignedDraftPurchaseOrders;
		private int? _NumUnAssignedIssuedPurchaseOrders;
		private int? _NumEmailNeedingManualProcessing;
		private System.DateTime? _LastGenerationEntryDate;
		private System.DateTime? _LatestGenerationEndDate;
		private System.DateTime? _LastBackupDate;
		private string _LastBackupFileName;

		public DatabaseStatus()
		{
		}
		/// Denotes the DatabaseStatus's Id column with type id(nonnull) with labelkey='Id'
		static public string DatabaseStatus_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumNewRequests column with type integer(32) with labelkey='NumNewRequests'
		static public string DatabaseStatus_NumNewRequests{ get{return AssignmentLabelKdsMBLabel.K("NumNewRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumNewRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumNewRequests", DbType="INT")]
		public int? NumNewRequests
		{
			get
			{
				return this._NumNewRequests;
			}
			set
			{
				if ((this._NumNewRequests != value))
				{
					this._NumNewRequests = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumInProgressRequests column with type integer(32) with labelkey='NumInProgressRequests'
		static public string DatabaseStatus_NumInProgressRequests{ get{return AssignmentLabelKdsMBLabel.K("NumInProgressRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumInProgressRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumInProgressRequests", DbType="INT")]
		public int? NumInProgressRequests
		{
			get
			{
				return this._NumInProgressRequests;
			}
			set
			{
				if ((this._NumInProgressRequests != value))
				{
					this._NumInProgressRequests = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedNewRequests column with type integer(32) with labelkey='NumUnAssignedNewRequests'
		static public string DatabaseStatus_NumUnAssignedNewRequests{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedNewRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedNewRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedNewRequests", DbType="INT")]
		public int? NumUnAssignedNewRequests
		{
			get
			{
				return this._NumUnAssignedNewRequests;
			}
			set
			{
				if ((this._NumUnAssignedNewRequests != value))
				{
					this._NumUnAssignedNewRequests = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedInProgressRequests column with type integer(32) with labelkey='NumUnAssignedInProgressRequests'
		static public string DatabaseStatus_NumUnAssignedInProgressRequests{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedInProgressRequests").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedInProgressRequests")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedInProgressRequests", DbType="INT")]
		public int? NumUnAssignedInProgressRequests
		{
			get
			{
				return this._NumUnAssignedInProgressRequests;
			}
			set
			{
				if ((this._NumUnAssignedInProgressRequests != value))
				{
					this._NumUnAssignedInProgressRequests = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumNewWorkOrders column with type integer(32) with labelkey='NumNewWorkOrders'
		static public string DatabaseStatus_NumNewWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumNewWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumNewWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumNewWorkOrders", DbType="INT")]
		public int? NumNewWorkOrders
		{
			get
			{
				return this._NumNewWorkOrders;
			}
			set
			{
				if ((this._NumNewWorkOrders != value))
				{
					this._NumNewWorkOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumOpenWorkOrders column with type integer(32) with labelkey='NumOpenWorkOrders'
		static public string DatabaseStatus_NumOpenWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumOpenWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumOpenWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOpenWorkOrders", DbType="INT")]
		public int? NumOpenWorkOrders
		{
			get
			{
				return this._NumOpenWorkOrders;
			}
			set
			{
				if ((this._NumOpenWorkOrders != value))
				{
					this._NumOpenWorkOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedNewWorkOrders column with type integer(32) with labelkey='NumUnAssignedNewWorkOrders'
		static public string DatabaseStatus_NumUnAssignedNewWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedNewWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedNewWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedNewWorkOrders", DbType="INT")]
		public int? NumUnAssignedNewWorkOrders
		{
			get
			{
				return this._NumUnAssignedNewWorkOrders;
			}
			set
			{
				if ((this._NumUnAssignedNewWorkOrders != value))
				{
					this._NumUnAssignedNewWorkOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedOpenWorkOrders column with type integer(32) with labelkey='NumUnAssignedOpenWorkOrders'
		static public string DatabaseStatus_NumUnAssignedOpenWorkOrders{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedOpenWorkOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedOpenWorkOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedOpenWorkOrders", DbType="INT")]
		public int? NumUnAssignedOpenWorkOrders
		{
			get
			{
				return this._NumUnAssignedOpenWorkOrders;
			}
			set
			{
				if ((this._NumUnAssignedOpenWorkOrders != value))
				{
					this._NumUnAssignedOpenWorkOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumDraftPurchaseOrders column with type integer(32) with labelkey='NumDraftPurchaseOrders'
		static public string DatabaseStatus_NumDraftPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumDraftPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumDraftPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDraftPurchaseOrders", DbType="INT")]
		public int? NumDraftPurchaseOrders
		{
			get
			{
				return this._NumDraftPurchaseOrders;
			}
			set
			{
				if ((this._NumDraftPurchaseOrders != value))
				{
					this._NumDraftPurchaseOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumIssuedPurchaseOrders column with type integer(32) with labelkey='NumIssuedPurchaseOrders'
		static public string DatabaseStatus_NumIssuedPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumIssuedPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumIssuedPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumIssuedPurchaseOrders", DbType="INT")]
		public int? NumIssuedPurchaseOrders
		{
			get
			{
				return this._NumIssuedPurchaseOrders;
			}
			set
			{
				if ((this._NumIssuedPurchaseOrders != value))
				{
					this._NumIssuedPurchaseOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedDraftPurchaseOrders column with type integer(32) with labelkey='NumUnAssignedDraftPurchaseOrders'
		static public string DatabaseStatus_NumUnAssignedDraftPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedDraftPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedDraftPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedDraftPurchaseOrders", DbType="INT")]
		public int? NumUnAssignedDraftPurchaseOrders
		{
			get
			{
				return this._NumUnAssignedDraftPurchaseOrders;
			}
			set
			{
				if ((this._NumUnAssignedDraftPurchaseOrders != value))
				{
					this._NumUnAssignedDraftPurchaseOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumUnAssignedIssuedPurchaseOrders column with type integer(32) with labelkey='NumUnAssignedIssuedPurchaseOrders'
		static public string DatabaseStatus_NumUnAssignedIssuedPurchaseOrders{ get{return AssignmentLabelKdsMBLabel.K("NumUnAssignedIssuedPurchaseOrders").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumUnAssignedIssuedPurchaseOrders")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumUnAssignedIssuedPurchaseOrders", DbType="INT")]
		public int? NumUnAssignedIssuedPurchaseOrders
		{
			get
			{
				return this._NumUnAssignedIssuedPurchaseOrders;
			}
			set
			{
				if ((this._NumUnAssignedIssuedPurchaseOrders != value))
				{
					this._NumUnAssignedIssuedPurchaseOrders = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's NumEmailNeedingManualProcessing column with type integer(32) with labelkey='NumEmailNeedingManualProcessing'
		static public string DatabaseStatus_NumEmailNeedingManualProcessing{ get{return AssignmentLabelKdsMBLabel.K("NumEmailNeedingManualProcessing").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_NumEmailNeedingManualProcessing")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumEmailNeedingManualProcessing", DbType="INT")]
		public int? NumEmailNeedingManualProcessing
		{
			get
			{
				return this._NumEmailNeedingManualProcessing;
			}
			set
			{
				if ((this._NumEmailNeedingManualProcessing != value))
				{
					this._NumEmailNeedingManualProcessing = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's LastGenerationEntryDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 00:00), by 24:00) with labelkey='LastGenerationEntryDate'
		static public string DatabaseStatus_LastGenerationEntryDate{ get{return AssignmentLabelKdsMBLabel.K("LastGenerationEntryDate").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_LastGenerationEntryDate")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastGenerationEntryDate", DbType="DATETIME")]
		public System.DateTime? LastGenerationEntryDate
		{
			get
			{
				return this._LastGenerationEntryDate;
			}
			set
			{
				if ((this._LastGenerationEntryDate != value))
				{
					this._LastGenerationEntryDate = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's LatestGenerationEndDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 00:00), by 24:00) with labelkey='LatestGenerationEndDate'
		static public string DatabaseStatus_LatestGenerationEndDate{ get{return AssignmentLabelKdsMBLabel.K("LatestGenerationEndDate").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_LatestGenerationEndDate")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatestGenerationEndDate", DbType="DATETIME")]
		public System.DateTime? LatestGenerationEndDate
		{
			get
			{
				return this._LatestGenerationEndDate;
			}
			set
			{
				if ((this._LatestGenerationEndDate != value))
				{
					this._LatestGenerationEndDate = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's LastBackupDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='LastBackupDate'
		static public string DatabaseStatus_LastBackupDate{ get{return AssignmentLabelKdsMBLabel.K("LastBackupDate").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_LastBackupDate")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastBackupDate", DbType="DATETIME")]
		public System.DateTime? LastBackupDate
		{
			get
			{
				return this._LastBackupDate;
			}
			set
			{
				if ((this._LastBackupDate != value))
				{
					this._LastBackupDate = value;
				}
			}
		}
		/// Denotes the DatabaseStatus's LastBackupFileName column with type string(minlength 1, maxlength 256, maxlines 0, trim) with labelkey='LastBackupFileName'
		static public string DatabaseStatus_LastBackupFileName{ get{return AssignmentLabelKdsMBLabel.K("LastBackupFileName").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.DatabaseStatus),Name="DatabaseStatus_LastBackupFileName")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastBackupFileName", DbType="NVARCHAR (256)")]
		public string LastBackupFileName
		{
			get
			{
				return this._LastBackupFileName;
			}
			set
			{
				if ((this._LastBackupFileName != value))
				{
					this._LastBackupFileName = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Request")]
	public partial class Request
	{
		// Denotes table Request with labelkey='Request'
		static public string RequestLabelKey { get{return AssignmentLabelKdsMBLabel.K("Request").Translate();}}
		private System.Guid _Id;

		public Request()
		{
		}
		/// Denotes the Request's Id column with type id(nonnull) with labelkey='Id'
		static public string Request_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.Request),Name="Request_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RequestAssignment")]
	public partial class RequestAssignment
	{
		// Denotes table RequestAssignment with labelkey='RequestAssignment'
		static public string RequestAssignmentLabelKey { get{return AssignmentLabelKdsMBLabel.K("RequestAssignment").Translate();}}
		private System.Guid _Id;

		public RequestAssignment()
		{
		}
		/// Denotes the RequestAssignment's Id column with type id(nonnull) with labelkey='Id'
		static public string RequestAssignment_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.RequestAssignment),Name="RequestAssignment_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkOrderAssignmentAll")]
	public partial class WorkOrderAssignmentAll
	{
		// Denotes table WorkOrderAssignmentAll with labelkey='WorkOrderAssignmentAll'
		static public string WorkOrderAssignmentAllLabelKey { get{return AssignmentLabelKdsMBLabel.K("WorkOrderAssignmentAll").Translate();}}
		private System.Guid _Id;

		public WorkOrderAssignmentAll()
		{
		}
		/// Denotes the WorkOrderAssignmentAll's Id column with type id(nonnull) with labelkey='Id'
		static public string WorkOrderAssignmentAll_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.WorkOrderAssignmentAll),Name="WorkOrderAssignmentAll_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseOrderAssignment")]
	public partial class PurchaseOrderAssignment
	{
		// Denotes table PurchaseOrderAssignment with labelkey='PurchaseOrderAssignment'
		static public string PurchaseOrderAssignmentLabelKey { get{return AssignmentLabelKdsMBLabel.K("PurchaseOrderAssignment").Translate();}}
		private System.Guid _Id;

		public PurchaseOrderAssignment()
		{
		}
		/// Denotes the PurchaseOrderAssignment's Id column with type id(nonnull) with labelkey='Id'
		static public string PurchaseOrderAssignment_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PurchaseOrderAssignment),Name="PurchaseOrderAssignment_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMGenerationBatch")]
	public partial class PMGenerationBatch
	{
		// Denotes table PMGenerationBatch with labelkey='PMGenerationBatch'
		static public string PMGenerationBatchLabelKey { get{return AssignmentLabelKdsMBLabel.K("PMGenerationBatch").Translate();}}
		private System.Guid _Id;

		public PMGenerationBatch()
		{
		}
		/// Denotes the PMGenerationBatch's Id column with type id(nonnull) with labelkey='Id'
		static public string PMGenerationBatch_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.PMGenerationBatch),Name="PMGenerationBatch_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BackupFileName")]
	public partial class BackupFileName
	{
		// Denotes table BackupFileName with labelkey='BackupFileName'
		static public string BackupFileNameLabelKey { get{return AssignmentLabelKdsMBLabel.K("BackupFileName").Translate();}}
		private System.Guid _Id;

		public BackupFileName()
		{
		}
		/// Denotes the BackupFileName's Id column with type id(nonnull) with labelkey='Id'
		static public string BackupFileName_Id{ get{return AssignmentLabelKdsMBLabel.K("Id").Translate();}}
		[System.ComponentModel.DataAnnotations.Display(ResourceType=typeof(AssignmentEntities.BackupFileName),Name="BackupFileName_Id")]		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UNIQUEIDENTIFIER", IsPrimaryKey=true)]
		[System.ComponentModel.DataAnnotations.Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Thinkage.Libraries.MVC.Models.FieldValidationResource))]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	internal class AssignmentLabelKdsMBLabel : Thinkage.Libraries.Translation.GeneralKeyBuilder {
		const string LabelContext = "dsMBLabel";

		static AssignmentLabelKdsMBLabel Instance = new AssignmentLabelKdsMBLabel();
		protected AssignmentLabelKdsMBLabel() {
		}
		protected override Thinkage.Libraries.Translation.ContextReference GetContext() {
			return Thinkage.Libraries.Translation.ContextReference.New(LabelContext);
		}
		public static Thinkage.Libraries.Translation.Key K([Thinkage.Libraries.Translation.Context(LabelContext)]string s) {
			return Instance.BuildKey(s);
		}
	}
}
#pragma warning restore 1591

