//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQueryUIHelpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JQueryUIHelpers.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datepicker requires DateTime or Nullable&lt;DateTime&gt;..
        /// </summary>
        internal static string DatepickerPropertyNotDateTime {
            get {
                return ResourceManager.GetString("DatepickerPropertyNotDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names parameter must contain exactly 7 names..
        /// </summary>
        internal static string DayNamesNotEqualSeven {
            get {
                return ResourceManager.GetString("DayNamesNotEqualSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one menu item must be defined..
        /// </summary>
        internal static string MenuWithoutItem {
            get {
                return ResourceManager.GetString("MenuWithoutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names parameter must contain exactly 12 names..
        /// </summary>
        internal static string MonthNamesNotEqualTwelve {
            get {
                return ResourceManager.GetString("MonthNamesNotEqualTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one handle must be defined..
        /// </summary>
        internal static string SliderWithoutHandle {
            get {
                return ResourceManager.GetString("SliderWithoutHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the field name using Sortable.Name before setting a value..
        /// </summary>
        internal static string SortableNameRequired {
            get {
                return ResourceManager.GetString("SortableNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab definition cannot be mixed with content panels..
        /// </summary>
        internal static string TabMixedWithContent {
            get {
                return ResourceManager.GetString("TabMixedWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab definition not found. Use AddTab before creating a new panel..
        /// </summary>
        internal static string UndefinedTab {
            get {
                return ResourceManager.GetString("UndefinedTab", resourceCulture);
            }
        }
    }
}
