



//-----------------------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by the XAFBuild tool.
//		Template file DBIGenerationTemplate.xml
//		Vault version 131
//		XAFBuild title: Thinkage.XAFBuild.StudioAddin in Thinkage ToolKit 3.0.3.0
//		Changes to this file will be lost if the code is regenerated.
// #defines
//  <TableName>RowChangedEvents to have row changed events enabled
//	DefineForeignKeyConstraints - for the ForeignKeyConstraints to be enabled
//	DefineUniqueConstraints - for the UniqueConstraints to be enabled
//  SerializationSupport - for the Serialization of the dataset Constructor to be enabled
// </autogenerated>
//-----------------------------------------------------------------------------------------------

namespace Thinkage.MainBoss.Database {
	using System.Linq;
	using System;
	using System.Xml;
	using System.Runtime.Serialization;
	using Thinkage.Libraries.XAF.Database.Layout;
	using Thinkage.Libraries.XAF.Database.Service;
	using Thinkage.Libraries.DBAccess;
	using System.Collections.Generic;

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2229:ImplementSerializationConstructors"), Serializable()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.ToolboxItem(true)]
	[Thinkage.Libraries.Translation.Invariant]
	public class dsBackupFileName_1_0_10_24 : DBDataSet {

		#region Database Variables VAccessor
		public VAccessor V {
			get {
				if (_V == null)
					_V = new VAccessor(this);
				return _V;
			}
		}
		private VAccessor _V;
		[Thinkage.Libraries.Translation.Invariant]
		public class VAccessor {
			#region Typed Variable Accessors
			#endregion
			#region VAccessor Construction
			public VAccessor(dsBackupFileName_1_0_10_24 this_dataset )
			{
			}
			#endregion
		}
		#endregion


		#region Custom DataSet Construction
		internal void CommonCTOR() {
			InitClass();
			Tables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_T = null;
				_DT = null;
			};
			VariablesChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_V = null;
			};
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		[Obsolete("Do not call this, it is only here to support DataSet.Clone.", true)]
		public dsBackupFileName_1_0_10_24() : base() {
			CommonCTOR();
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public dsBackupFileName_1_0_10_24(DBClient db) : base(Schema, db) {
			CommonCTOR();
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public dsBackupFileName_1_0_10_24(IServer server) : base(Schema, server) {
			CommonCTOR();
		}
#if SerializationSupport
		protected dsBackupFileName_1_0_10_24(SerializationInfo info, StreamingContext context) {
			/// ExtendedProperties are not copied in this CTOR if they are not part of the input stream. In particular, any delgate extended properties
			/// we put on datatables may not be copied. If we end up with any delegate extended properties on datatables, then we will need to
			/// amend the code below to propogate the properties itself
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) {
				var ds = new System.Data.DataSet();
				ds.ReadXmlSchema(XmlReader.Create(new System.IO.StringReader(strSchema)));
				TODO: Variables need streaming support
				if ((ds.Tables.FindTableDuringTableConstruction(SchemaClass.Instance.T.BackupFileName) != null)) {
					this.Tables.Add(new BackupFileNameDataTable(ds.Tables.FindTableDuringTableConstruction(SchemaClass.Instance.T.BackupFileName)));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			}
			else
				this.InitClass();

			this.GetSerializationData(info, context);
			Tables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_T = null;
				_DT = null;
			};
			DataVariables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_V = null;
			};
		}
#endif
		protected override void InitClass() {
			this.DataSetName = "dsBackupFileName_1_0_10_24";
			this.Prefix = "";
			this.EnforceConstraints = false;
			base.InitClass();
			#region Foreign Key Constraints
			#if DefineForeignKeyConstraints

			#endif
			#endregion

		}
		#endregion

		#region Table Accessor Struct
		public TAccessor T {
			get {
				if (_T == null)
					_T = new TAccessor(this);
				return _T;
			}
		}
		private TAccessor _T;
		public class TAccessor {
			public TAccessor( dsBackupFileName_1_0_10_24 this_dataset ) {
				this.BackupFileName = (BackupFileNameDataTable)this_dataset.Tables.FindTableDuringTableConstruction(SchemaClass.Instance.T.BackupFileName);
			}
			public readonly BackupFileNameDataTable BackupFileName;
		}
		#endregion
		#region Default-table accessor struct
		public DTAccessor DT {
			get {
				if (_DT == null)
					_DT = new DTAccessor(this);
				return _DT;
			}
		}
		private DTAccessor _DT;
		public class DTAccessor {
			public DTAccessor( dsBackupFileName_1_0_10_24 this_dataset ) {
			}
		}
		#endregion
		#region DataSet Streaming
		#if SerializationSupport
		protected override bool ShouldSerializeTables() {
			return false;
		}
		protected override bool ShouldSerializeRelations() {
			return false;
		}
		protected override void ReadXmlSerializable(XmlReader reader) {
			this.Reset();
			var ds = new System.Data.DataSet();
			ds.ReadXml(reader);
			TODO: Variables need streaming support
			if ((ds.Tables.FindTableDuringTableConstruction(SchemaClass.Instance.T.BackupFileName) != null)) {
				this.Tables.Add(new BackupFileNameDataTable(ds.Tables.FindTableDuringTableConstruction(SchemaClass.Instance.T.BackupFileName)));
			}
			this.DataSetName = ds.DataSetName;
			this.Prefix = ds.Prefix;
			this.Namespace = ds.Namespace;
			this.Locale = ds.Locale;
			this.CaseSensitive = ds.CaseSensitive;
			this.EnforceConstraints = ds.EnforceConstraints;
			this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			this.InitVars();
		}
		protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
			System.IO.MemoryStream stream = new System.IO.MemoryStream();
			this.WriteXmlSchema(XmlWriter.Create(stream));
			stream.Position = 0;
			return System.Xml.Schema.XmlSchema.Read(XmlReader.Create(stream), null);
		}
		#endif
		#endregion

		#region Custom-derived DataTable Classes
		#region BackupFileNameDataTable
		private bool ShouldSerializeBackupFileName() {
			return false;
		}
#if BackupFileNameRowChangeEvents
		public delegate void BackupFileNameRowChangeEventHandler(object sender, BackupFileNameRowChangeEvent e);
#endif

		[Thinkage.Libraries.Translation.Invariant]
		public class BackupFileNameDataTable : DBICustomDataTable<BackupFileNameRow> {
			#region Construction
			internal BackupFileNameDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal BackupFileNameDataTable(System.Data.DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(BackupFileNameDataTable t) {
				  this.Id = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.Id);
				  this.LastBackupDate = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.LastBackupDate);
				  this.FileName = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.FileName);
				  this.Comment = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.Comment);
				  this.Message = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.Message);
				  this.DatabaseVersion = t.Columns.FindColumnDuringTableConstruction(SchemaClass.Instance.T.BackupFileName.F.DatabaseVersion);
				}
				/// <summary>
				/// Denotes the BackupFileName's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the BackupFileName's LastBackupDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='LastBackupDate'
				/// </summary>
				public readonly DBIDataColumn LastBackupDate;
				/// <summary>
				/// Denotes the BackupFileName's FileName column with type string(nonnull, minlength 1, maxlength 256, maxlines 0, trim) with labelkey='FileName'
				/// </summary>
				public readonly DBIDataColumn FileName;
				/// <summary>
				/// Denotes the BackupFileName's Comment column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Comment'
				/// </summary>
				public readonly DBIDataColumn Comment;
				/// <summary>
				/// Denotes the BackupFileName's Message column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Message'
				/// </summary>
				public readonly DBIDataColumn Message;
				/// <summary>
				/// Denotes the BackupFileName's DatabaseVersion column with type string(minlength 1, maxlength 23, maxlines 0) with labelkey='DatabaseVersion'
				/// </summary>
				public readonly DBIDataColumn DatabaseVersion;
			}
			#endregion
			#region EventHandlers
			#if BackupFileNameRowChangeEvents
			public event BackupFileNameRowChangeEventHandler BackupFileNameRowChanged;
			public event BackupFileNameRowChangeEventHandler BackupFileNameRowChanging;
			public event BackupFileNameRowChangeEventHandler BackupFileNameRowDeleted;
			public event BackupFileNameRowChangeEventHandler BackupFileNameRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.BackupFileNameRowChanged?.Invoke(this, new BackupFileNameRowChangeEvent(((BackupFileNameRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.BackupFileNameRowChanging?.Invoke(this, new BackupFileNameRowChangeEvent(((BackupFileNameRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.BackupFileNameRowDeleted?.Invoke(this, new BackupFileNameRowChangeEvent(((BackupFileNameRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.BackupFileNameRowDeleting?.Invoke(this, new BackupFileNameRowChangeEvent(((BackupFileNameRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			protected override DBIDataTable CreateDBIInstance() => new BackupFileNameDataTable(Schema, Server);
			public BackupFileNameRow AddNewRow() => (BackupFileNameRow)DataSet.DB.AddNewRowAndBasesForGeneratedClass(DataSet, dsBackupFileName_1_0_10_24.Schema.T.BackupFileName);
			protected override DBIDataRow NewDBIRowFromBuilder(System.Data.DataRowBuilder builder) => new BackupFileNameRow(builder);
			public new dsBackupFileName_1_0_10_24 DataSet => (dsBackupFileName_1_0_10_24)base.DataSet;
		}
		#region BackupFileNameRow
		[Thinkage.Libraries.Translation.Invariant]
		public class BackupFileNameRow : DBICustomDataRow<BackupFileNameDataTable> {
			#region Construction
			internal BackupFileNameRow(System.Data.DataRowBuilder rb)
				: base(rb) {
			}
			#endregion
			#region Typed Column accessor
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly BackupFileNameDataTable this_table;
				private readonly BackupFileNameRow this_row;
				public FAccessor( BackupFileNameRow this_row )
				{
					this.this_table = ((BackupFileNameDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the BackupFileName's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.BackupFileName.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the BackupFileName's LastBackupDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='LastBackupDate'
				/// </summary>
				public System.DateTime? LastBackupDate {
					get {
							return (System.DateTime?)Schema.T.BackupFileName.F.LastBackupDate.EffectiveType.GenericAsNativeType(this_table.F.LastBackupDate[this_row], typeof(System.DateTime?));
					}
					set {this_table.F.LastBackupDate[this_row] = value; }
				}
				/// <summary>
				/// Denotes the BackupFileName's FileName column with type string(nonnull, minlength 1, maxlength 256, maxlines 0, trim) with labelkey='FileName'
				/// </summary>
				public System.String FileName {
					get {
							return (System.String)Schema.T.BackupFileName.F.FileName.EffectiveType.GenericAsNativeType(this_table.F.FileName[this_row], typeof(System.String));
					}
					set {this_table.F.FileName[this_row] = value; }
				}
				/// <summary>
				/// Denotes the BackupFileName's Comment column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Comment'
				/// </summary>
				public System.String Comment {
					get {
							return (System.String)Schema.T.BackupFileName.F.Comment.EffectiveType.GenericAsNativeType(this_table.F.Comment[this_row], typeof(System.String));
					}
					set {this_table.F.Comment[this_row] = value; }
				}
				/// <summary>
				/// Denotes the BackupFileName's Message column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Message'
				/// </summary>
				public System.String Message {
					get {
							return (System.String)Schema.T.BackupFileName.F.Message.EffectiveType.GenericAsNativeType(this_table.F.Message[this_row], typeof(System.String));
					}
					set {this_table.F.Message[this_row] = value; }
				}
				/// <summary>
				/// Denotes the BackupFileName's DatabaseVersion column with type string(minlength 1, maxlength 23, maxlines 0) with labelkey='DatabaseVersion'
				/// </summary>
				public System.String DatabaseVersion {
					get {
							return (System.String)Schema.T.BackupFileName.F.DatabaseVersion.EffectiveType.GenericAsNativeType(this_table.F.DatabaseVersion[this_row], typeof(System.String));
					}
					set {this_table.F.DatabaseVersion[this_row] = value; }
				}
			}
			#endregion
			#region Referenced-record accessors
			#endregion
			#region Referring-record accessors
			#endregion
		}
		#endregion
		#region BackupFileNameRowChangeEvent
#if BackupFileNameRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class BackupFileNameRowChangeEvent : EventArgs {

			private BackupFileNameRow eventRow;

			private DataRowAction eventAction;

			public BackupFileNameRowChangeEvent(BackupFileNameRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public BackupFileNameRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#endregion

		#region Custom database schema definitions
		#region - the custom Schema class
		/// <summary>
		/// Singleton class containing the schema of all tables,
		/// columns, and relationships in a database.
		/// </summary>
		[Thinkage.Libraries.Translation.Invariant]
		public class SchemaClass : DBI_Database {
			#region singleton construction
			private SchemaClass() {
				_T = new TAccessor(this);
				vstruct = new VAccessor(this);
				__BackupFileName = new DBI_BackupFileName();
				Tables.Add( __BackupFileName);
				CompleteDBI(System.Reflection.Assembly.GetExecutingAssembly(), "manifest://localhost/Thinkage/MainBoss/Database/Upgrade/Schema/dsBackupFileName_1_0_10_24.xafdb", typeof(dsBackupFileName_1_0_10_24)
				);
			 }
			/// <summary>
			/// The instantiation of the singleton SchemaClass object
			/// </summary>
			public static readonly SchemaClass Instance = new SchemaClass();
			#endregion
			#region Custom DBI_Table derivations and their private reference in the schema object
			#region - BackupFileName table
			private DBI_BackupFileName __BackupFileName;

			/// <summary>
			/// Class to describe a BackupFileName table
			/// </summary>
			public class DBI_BackupFileName : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __LastBackupDate;
				private DBI_Column __FileName;
				private DBI_Column __Comment;
				private DBI_Column __Message;
				private DBI_Column __DatabaseVersion;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_BackupFileName this_table;
					public FAccessor( DBI_BackupFileName this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the BackupFileName's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the BackupFileName's LastBackupDate column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='LastBackupDate'
					/// </summary>
					public DBI_Column LastBackupDate { get { return this_table.__LastBackupDate; } }
					/// <summary>
					/// Denotes the BackupFileName's FileName column with type string(nonnull, minlength 1, maxlength 256, maxlines 0, trim) with labelkey='FileName'
					/// </summary>
					public DBI_Column FileName { get { return this_table.__FileName; } }
					/// <summary>
					/// Denotes the BackupFileName's Comment column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Comment'
					/// </summary>
					public DBI_Column Comment { get { return this_table.__Comment; } }
					/// <summary>
					/// Denotes the BackupFileName's Message column with type string(minlength 1, (maxlength 1,073,741,823), trim) with labelkey='Message'
					/// </summary>
					public DBI_Column Message { get { return this_table.__Message; } }
					/// <summary>
					/// Denotes the BackupFileName's DatabaseVersion column with type string(minlength 1, maxlength 23, maxlines 0) with labelkey='DatabaseVersion'
					/// </summary>
					public DBI_Column DatabaseVersion { get { return this_table.__DatabaseVersion; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_BackupFileName()
					: base("BackupFileName", (DBI_Table tableSchema, IServer s) => new BackupFileNameDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 6, "Table 'BackupFileName' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__LastBackupDate = Columns["LastBackupDate"];
					System.Diagnostics.Debug.Assert(__LastBackupDate != null, "Column 'LastBackupDate' not found");
					__FileName = Columns["FileName"];
					System.Diagnostics.Debug.Assert(__FileName != null, "Column 'FileName' not found");
					__Comment = Columns["Comment"];
					System.Diagnostics.Debug.Assert(__Comment != null, "Column 'Comment' not found");
					__Message = Columns["Message"];
					System.Diagnostics.Debug.Assert(__Message != null, "Column 'Message' not found");
					__DatabaseVersion = Columns["DatabaseVersion"];
					System.Diagnostics.Debug.Assert(__DatabaseVersion != null, "Column 'DatabaseVersion' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#endregion
			#region T - the public portal for getting the custom-typed DBI_Table objects for each table
			public struct TAccessor {
				private SchemaClass this_schema;
				public TAccessor( SchemaClass this_schema )
				{
					this.this_schema = this_schema;
				}
				#region Accessors
				/// <summary>
				/// Denotes the BackupFileName table with labelkey='BackupFileName'
				/// </summary>
				public DBI_BackupFileName BackupFileName { get { return this_schema.__BackupFileName; }}
				#endregion
			}
			public TAccessor T { get { return _T; } }
			private TAccessor _T;
			#endregion
			#region V - the public portal for getting the DBI_Variable objects for Database Variables
			public struct VAccessor {
				private SchemaClass this_schema;
				public VAccessor( SchemaClass this_schema )
				{
					this.this_schema = this_schema;
				}
				#region Variable Accessors
				#endregion
			}
			public VAccessor V { get { return vstruct; } }	// Variables
			private VAccessor vstruct;
			#endregion
		}
		#endregion
		#region - The static member that contains the Schema
		public readonly static SchemaClass Schema = SchemaClass.Instance;
		// make a member variable in the class for reference in a dynamic type instance of this object
		public readonly SchemaClass SchemaDynamic = Schema;
		#endregion
		#endregion
		#region Database Path definitions
		[Thinkage.Libraries.Translation.Invariant]
		public class PathClass {
			/// <summary>
			/// Class containing the relationship paths of all tables,
			/// </summary>
			public readonly TAccessor T;
			/// <summary>
			/// Private constructor for singleton creation
			/// </summary>
			private PathClass() {
				T = new TAccessor(this);
			}

			/// <summary>
			/// The instantiation of the singleton Path object
			/// </summary>
			public static readonly PathClass Instance = new PathClass();
			#region DBI_Path Definitions

			#region DBI_Path BackupFileName
			private PathToBackupFileNameRow __pBackupFileName = new PathToBackupFileNameRow( SchemaClass.Instance.T.BackupFileName );

			/// <summary>
			/// The BackupFileName path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToBackupFileNameRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToField _LastBackupDate;
				private PathToField _FileName;
				private PathToField _Comment;
				private PathToField _Message;
				private PathToField _DatabaseVersion;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToBackupFileNameRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToBackupFileNameRow _BasePath;
					/// <summary>
					/// Provides the path to BackupFileName's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.BackupFileName.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to BackupFileName's LastBackupDate with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) and labelkey='LastBackupDate'
					/// </summary>
					public PathToField LastBackupDate { get { if (_BasePath._LastBackupDate == null) _BasePath._LastBackupDate = new PathToField(_BasePath, Schema.T.BackupFileName.F.LastBackupDate ); return _BasePath._LastBackupDate; } }
					/// <summary>
					/// Provides the path to BackupFileName's FileName with type string(nonnull, minlength 1, maxlength 256, maxlines 0, trim) and labelkey='FileName'
					/// </summary>
					public PathToField FileName { get { if (_BasePath._FileName == null) _BasePath._FileName = new PathToField(_BasePath, Schema.T.BackupFileName.F.FileName ); return _BasePath._FileName; } }
					/// <summary>
					/// Provides the path to BackupFileName's Comment with type string(minlength 1, (maxlength 1,073,741,823), trim) and labelkey='Comment'
					/// </summary>
					public PathToField Comment { get { if (_BasePath._Comment == null) _BasePath._Comment = new PathToField(_BasePath, Schema.T.BackupFileName.F.Comment ); return _BasePath._Comment; } }
					/// <summary>
					/// Provides the path to BackupFileName's Message with type string(minlength 1, (maxlength 1,073,741,823), trim) and labelkey='Message'
					/// </summary>
					public PathToField Message { get { if (_BasePath._Message == null) _BasePath._Message = new PathToField(_BasePath, Schema.T.BackupFileName.F.Message ); return _BasePath._Message; } }
					/// <summary>
					/// Provides the path to BackupFileName's DatabaseVersion with type string(minlength 1, maxlength 23, maxlines 0) and labelkey='DatabaseVersion'
					/// </summary>
					public PathToField DatabaseVersion { get { if (_BasePath._DatabaseVersion == null) _BasePath._DatabaseVersion = new PathToField(_BasePath, Schema.T.BackupFileName.F.DatabaseVersion ); return _BasePath._DatabaseVersion; } }
				}

				internal PathToBackupFileNameRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToBackupFileNameRow( DBI_Table t ) : base( t ) { }
				internal PathToBackupFileNameRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToBackupFileNameLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToBackupFileNameRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToBackupFileNameRow PathToReferencedRow { get { return (PathToBackupFileNameRow)base.PathToReferencedRow; } }

				internal PathToBackupFileNameLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToBackupFileNameRow(rootTableSchema, columns);
				}
			}
			public class LinkToBackupFileName {
				public LinkToBackupFileName(DBI_Path referencing_path) {
					Id = new PathToBackupFileNameRow(referencing_path.PathThroughLinkage(Schema.T.BackupFileName.F.Id));
					FileName = new PathToBackupFileNameRow(referencing_path.PathThroughLinkage(Schema.T.BackupFileName.F.FileName));
				}
				public readonly PathToBackupFileNameRow Id;
				public readonly PathToBackupFileNameRow FileName;
			}
			#endregion
			public class PathToField : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				[System.Obsolete("This field is not a linkage field", true)]
				public new PathToField PathToReferencedRow { get { return null; } }

				internal PathToField( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
			}
			#endregion
			public struct TAccessor {
				private PathClass this_path;
				public TAccessor( PathClass this_path )
				{
					this.this_path = this_path;
				}
				#region Accessors
				/// <summary>
				/// Provides the root path for BackupFileName with labelkey='BackupFileName'
				/// </summary>
				public PathToBackupFileNameRow BackupFileName { get { return this_path.__pBackupFileName; } }
				#endregion
			}
			public class LAccessorBase {
				protected LAccessorBase(DBI_Path basePath) {
					BasePath = basePath;
				}
				protected readonly DBI_Path BasePath;
				#region Cached Accessor results
				protected PathClass.LinkToBackupFileName _BackupFileName;
				#endregion
			}
			public class LAccessor : LAccessorBase {
				public LAccessor( DBI_Path this_path ) 
					: base(this_path) {
				}
				#region Accessors
				public PathClass.LinkToBackupFileName BackupFileName { get { if (base._BackupFileName == null) base._BackupFileName = new PathClass.LinkToBackupFileName(base.BasePath); return base._BackupFileName; } }
				#endregion
			}
		}
		public static readonly PathClass Path = PathClass.Instance;
		#endregion
		#region Label Key Building
		public class LabelKeyBuilder : Thinkage.Libraries.Translation.GeneralKeyBuilder {
			static LabelKeyBuilder Instance = new LabelKeyBuilder();
			private LabelKeyBuilder() {
			}
			protected override Thinkage.Libraries.Translation.ContextReference GetContext() {
				return Thinkage.Libraries.Translation.ContextReference.New("");
			}
			public static Thinkage.Libraries.Translation.Key K([Thinkage.Libraries.Translation.Context("")]string s) {
				return Instance.BuildKey(s);
			}
		}
		#endregion
	}
}
