



//-----------------------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by the XAFBuild tool.
//		Template file DBIGenerationTemplate.xml
//		Vault version 116
//		XAFBuild title: Thinkage.XAFBuild.StudioAddin in Thinkage ToolKit 3.0.0.0
//		Changes to this file will be lost if the code is regenerated.
// #defines
//  <TableName>RowChangedEvents to have row changed events enabled
//	DefineForeignKeyConstraints - for the ForeignKeyConstraints to be enabled
//	DefineUniqueConstraints - for the UniqueConstraints to be enabled
//  SerializationSupport - for the Serialization of the dataset Constructor to be enabled
// </autogenerated>
//-----------------------------------------------------------------------------------------------

namespace Thinkage.MainBoss.Database {
	using System.Linq;
	using System;
	using System.Data;
	using System.Xml;
	using System.Runtime.Serialization;
	using Thinkage.Libraries.DBILibrary;
	using Thinkage.Libraries.DBAccess;
	using System.Collections.Generic;

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2229:ImplementSerializationConstructors"), Serializable()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.ComponentModel.ToolboxItem(true)]
	[Thinkage.Libraries.Translation.Invariant]
	public class dsPermission_1_1_4_2 : DBDataSet {

		#region Database Variables VAccessor
		public VAccessor V {
			get {
				if (_V == null)
					_V = new VAccessor(this);
				return _V;
			}
		}
		private VAccessor _V;
		[Thinkage.Libraries.Translation.Invariant]
		public class VAccessor {
			#region Typed Variable Accessors
			#endregion
			#region VAccessor Construction
			public VAccessor(dsPermission_1_1_4_2 this_dataset )
			{
			}
			#endregion
		}
		#endregion


		#region DataSet Construction

		internal void CommonCTOR() {
			InitClass();
			Tables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_T = null;
				_DT = null;
			};
			VariablesChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_V = null;
			};
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		[Obsolete("Do not call this, it is only here to support DataSet.Clone.", true)]
		public dsPermission_1_1_4_2() : base() {
			CommonCTOR();
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public dsPermission_1_1_4_2(DBClient db) : base(Schema, db) {
			CommonCTOR();
		}
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public dsPermission_1_1_4_2(IServer server) : base(Schema, server) {
			CommonCTOR();
		}
#if SerializationSupport
		protected dsPermission_1_1_4_2(SerializationInfo info, StreamingContext context) {
			/// ExtendedProperties are not copied in this CTOR if they are not part of the input stream. In particular, any delgate extended properties
			/// we put on datatables may not be copied. If we end up with any delegate extended properties on datatables, then we will need to
			/// amend the code below to propogate the properties itself
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) {
				DataSet ds = new DataSet();
				ds.ReadXmlSchema(XmlReader.Create(new System.IO.StringReader(strSchema)));
				if (ds.Tables["__Variables"] != null)
					this.Tables.Add( new DataVariable.__VariablesDataTable(ds.Tables["__Variables"]));
				if ((ds.Tables["Permission"] != null)) {
					this.Tables.Add(new PermissionDataTable(ds.Tables["Permission"]));
				}
				if ((ds.Tables["Principal"] != null)) {
					this.Tables.Add(new PrincipalDataTable(ds.Tables["Principal"]));
				}
				if ((ds.Tables["Role"] != null)) {
					this.Tables.Add(new RoleDataTable(ds.Tables["Role"]));
				}
				if ((ds.Tables["User"] != null)) {
					this.Tables.Add(new UserDataTable(ds.Tables["User"]));
				}
				if ((ds.Tables["UserRole"] != null)) {
					this.Tables.Add(new UserRoleDataTable(ds.Tables["UserRole"]));
				}
				if ((ds.Tables["UserPermission"] != null)) {
					this.Tables.Add(new UserPermissionDataTable(ds.Tables["UserPermission"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			}
			else
				this.InitClass();

			this.GetSerializationData(info, context);
			Tables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_T = null;
				_DT = null;
			};
			DataVariables.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
				_V = null;
			};
		}
#endif

		protected override void InitClass() {
			this.DataSetName = "dsPermission_1_1_4_2";
			this.Prefix = "";
			this.EnforceConstraints = false;
			base.InitClass();
			#region Foreign Key Constraints
			#if DefineForeignKeyConstraints

			ForeignKeyConstraint fkc;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tablePrincipal.IdColumn}, new DataColumn[] {
						this.tablePermission.F.PrincipalID});
			this.tablePermission.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tableRole.IdColumn}, new DataColumn[] {
						this.tablePrincipal.F.RoleID});
			this.tablePrincipal.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tableUser.IdColumn}, new DataColumn[] {
						this.tablePrincipal.F.UserID});
			this.tablePrincipal.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tablePrincipal.IdColumn}, new DataColumn[] {
						this.tableRole.F.PrincipalID});
			this.tableRole.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.Cascade;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tablePrincipal.IdColumn}, new DataColumn[] {
						this.tableUser.F.PrincipalID});
			this.tableUser.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.Cascade;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tablePrincipal.IdColumn}, new DataColumn[] {
						this.tableUserRole.F.PrincipalID});
			this.tableUserRole.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tableUser.IdColumn}, new DataColumn[] {
						this.tableUserRole.F.UserID});
			this.tableUserRole.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			fkc = new ForeignKeyConstraint("", new DataColumn[] {
						this.tableUser.IdColumn}, new DataColumn[] {
						this.tableUserPermission.F.UserID});
			this.tableUserPermission.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.None;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			#endif
			#endregion

		}
		#endregion

		#region Table Accessor Struct
		public TAccessor T {
			get {
				if (_T == null)
					_T = new TAccessor(this);
				return _T;
			}
		}
		private TAccessor _T;
		public class TAccessor {
			public TAccessor( dsPermission_1_1_4_2 this_dataset ) {
				this.Permission = (PermissionDataTable)this_dataset.Tables["Permission"];
				this.Principal = (PrincipalDataTable)this_dataset.Tables["Principal"];
				this.Role = (RoleDataTable)this_dataset.Tables["Role"];
				this.User = (UserDataTable)this_dataset.Tables["User"];
				this.UserRole = (UserRoleDataTable)this_dataset.Tables["UserRole"];
				this.UserPermission = (UserPermissionDataTable)this_dataset.Tables["UserPermission"];
			}
			public readonly PermissionDataTable Permission;
			public readonly PrincipalDataTable Principal;
			public readonly RoleDataTable Role;
			public readonly UserDataTable User;
			public readonly UserRoleDataTable UserRole;
			public readonly UserPermissionDataTable UserPermission;
		}
		#endregion
		#region Default-table accessor struct
		public DTAccessor DT {
			get {
				if (_DT == null)
					_DT = new DTAccessor(this);
				return _DT;
			}
		}
		private DTAccessor _DT;
		public class DTAccessor {
			public DTAccessor( dsPermission_1_1_4_2 this_dataset ) {
				this.Permission = (PermissionDataTable)this_dataset.Tables["_DPermission"];
				this.Principal = (PrincipalDataTable)this_dataset.Tables["_DPrincipal"];
				this.Role = (RoleDataTable)this_dataset.Tables["_DRole"];
				this.User = (UserDataTable)this_dataset.Tables["_DUser"];
				this.UserRole = (UserRoleDataTable)this_dataset.Tables["_DUserRole"];
				this.UserPermission = (UserPermissionDataTable)this_dataset.Tables["_DUserPermission"];
			}
			public readonly PermissionDataTable Permission;
			public readonly PrincipalDataTable Principal;
			public readonly RoleDataTable Role;
			public readonly UserDataTable User;
			public readonly UserRoleDataTable UserRole;
			public readonly UserPermissionDataTable UserPermission;
		}
		#endregion
		#region DataSet Streaming
		#if SerializationSupport
		protected override bool ShouldSerializeTables() {
			return false;
		}
		protected override bool ShouldSerializeRelations() {
			return false;
		}
		protected override void ReadXmlSerializable(XmlReader reader) {
			this.Reset();
			DataSet ds = new DataSet();
			ds.ReadXml(reader);
			if ((ds.Tables["__Variables"] != null))
				this.Tables.Add( new DataVariable.__VariablesDataTable(ds.Tables["__Variables"]));
			if ((ds.Tables["Permission"] != null)) {
				this.Tables.Add(new PermissionDataTable(ds.Tables["Permission"]));
			}
			if ((ds.Tables["Principal"] != null)) {
				this.Tables.Add(new PrincipalDataTable(ds.Tables["Principal"]));
			}
			if ((ds.Tables["Role"] != null)) {
				this.Tables.Add(new RoleDataTable(ds.Tables["Role"]));
			}
			if ((ds.Tables["User"] != null)) {
				this.Tables.Add(new UserDataTable(ds.Tables["User"]));
			}
			if ((ds.Tables["UserRole"] != null)) {
				this.Tables.Add(new UserRoleDataTable(ds.Tables["UserRole"]));
			}
			if ((ds.Tables["UserPermission"] != null)) {
				this.Tables.Add(new UserPermissionDataTable(ds.Tables["UserPermission"]));
			}
			this.DataSetName = ds.DataSetName;
			this.Prefix = ds.Prefix;
			this.Namespace = ds.Namespace;
			this.Locale = ds.Locale;
			this.CaseSensitive = ds.CaseSensitive;
			this.EnforceConstraints = ds.EnforceConstraints;
			this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			this.InitVars();
		}
		protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
			System.IO.MemoryStream stream = new System.IO.MemoryStream();
			this.WriteXmlSchema(XmlWriter.Create(stream));
			stream.Position = 0;
			return System.Xml.Schema.XmlSchema.Read(XmlReader.Create(stream), null);
		}
		#endif
		#endregion

		#region DataTable Classes
		#region Permission
		private bool ShouldSerializePermission() {
			return false;
		}
#if PermissionRowChangeEvents
		public delegate void PermissionRowChangeEventHandler(object sender, PermissionRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class PermissionDataTable : DBIDataTable {
			#region Construction
			internal PermissionDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal PermissionDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(PermissionDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.PrincipalID = (DBIDataColumn)t.Columns["PrincipalID"];
				  this.PermissionPathPattern = (DBIDataColumn)t.Columns["PermissionPathPattern"];
				}
				/// <summary>
				/// Denotes the Permission's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the Permission's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public readonly DBIDataColumn PrincipalID;
				/// <summary>
				/// Denotes the Permission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
				/// </summary>
				public readonly DBIDataColumn PermissionPathPattern;
			}
			#endregion
			#region EventHandlers
			#if PermissionRowChangeEvents
			public event PermissionRowChangeEventHandler PermissionRowChanged;
			public event PermissionRowChangeEventHandler PermissionRowChanging;
			public event PermissionRowChangeEventHandler PermissionRowDeleted;
			public event PermissionRowChangeEventHandler PermissionRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.PermissionRowChanged?.Invoke(this, new PermissionRowChangeEvent(((PermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.PermissionRowChanging?.Invoke(this, new PermissionRowChangeEvent(((PermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.PermissionRowDeleted?.Invoke(this, new PermissionRowChangeEvent(((PermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.PermissionRowDeleting?.Invoke(this, new PermissionRowChangeEvent(((PermissionRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new PermissionDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public PermissionRow this[int index] {
				get {
					return ((PermissionRow)(this.Rows[index]));
				}
			}
			public void AddPermissionRow(PermissionRow row) {
				this.Rows.Add(row);
			}
			public PermissionRow AddNewPermissionRow() {
				return ((PermissionRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.Permission)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new PermissionRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(PermissionRow);
			}
			public void RemovePermissionRow(PermissionRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region PermissionRow
		[Thinkage.Libraries.Translation.Invariant]
		public class PermissionRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal PermissionRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly PermissionDataTable this_table;
				private readonly PermissionRow this_row;
				public FAccessor( PermissionRow this_row )
				{
					this.this_table = ((PermissionDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the Permission's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.Permission.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the Permission's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public System.Guid PrincipalID {
					get {
							return (System.Guid)Schema.T.Permission.F.PrincipalID.EffectiveType.GenericAsNativeType(this_table.F.PrincipalID[this_row], typeof(System.Guid));
					}
					set {this_table.F.PrincipalID[this_row] = value; }
				}
				/// <summary>
				/// Denotes the Permission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
				/// </summary>
				public System.String PermissionPathPattern {
					get {
							return (System.String)Schema.T.Permission.F.PermissionPathPattern.EffectiveType.GenericAsNativeType(this_table.F.PermissionPathPattern[this_row], typeof(System.String));
					}
					set {this_table.F.PermissionPathPattern[this_row] = value; }
				}
			}
			public PrincipalRow PrincipalIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.RowFind<PrincipalRow>(F.PrincipalID);
				}
			}

		}
		#endregion
		#region PermissionRowChangeEvent
#if PermissionRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class PermissionRowChangeEvent : EventArgs {

			private PermissionRow eventRow;

			private DataRowAction eventAction;

			public PermissionRowChangeEvent(PermissionRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public PermissionRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#region Principal
		private bool ShouldSerializePrincipal() {
			return false;
		}
#if PrincipalRowChangeEvents
		public delegate void PrincipalRowChangeEventHandler(object sender, PrincipalRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class PrincipalDataTable : DBIDataTable {
			#region Construction
			internal PrincipalDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal PrincipalDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(PrincipalDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.RoleID = (DBIDataColumn)t.Columns["RoleID"];
				  this.UserID = (DBIDataColumn)t.Columns["UserID"];
				}
				/// <summary>
				/// Denotes the Principal's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the Principal's RoleID column with type link(field Role.Id) with labelkey='Role'
				/// </summary>
				public readonly DBIDataColumn RoleID;
				/// <summary>
				/// Denotes the Principal's UserID column with type link(field User.Id) with labelkey='User'
				/// </summary>
				public readonly DBIDataColumn UserID;
			}
			#endregion
			#region EventHandlers
			#if PrincipalRowChangeEvents
			public event PrincipalRowChangeEventHandler PrincipalRowChanged;
			public event PrincipalRowChangeEventHandler PrincipalRowChanging;
			public event PrincipalRowChangeEventHandler PrincipalRowDeleted;
			public event PrincipalRowChangeEventHandler PrincipalRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.PrincipalRowChanged?.Invoke(this, new PrincipalRowChangeEvent(((PrincipalRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.PrincipalRowChanging?.Invoke(this, new PrincipalRowChangeEvent(((PrincipalRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.PrincipalRowDeleted?.Invoke(this, new PrincipalRowChangeEvent(((PrincipalRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.PrincipalRowDeleting?.Invoke(this, new PrincipalRowChangeEvent(((PrincipalRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new PrincipalDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public PrincipalRow this[int index] {
				get {
					return ((PrincipalRow)(this.Rows[index]));
				}
			}
			public void AddPrincipalRow(PrincipalRow row) {
				this.Rows.Add(row);
			}
			public PrincipalRow AddNewPrincipalRow() {
				return ((PrincipalRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.Principal)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new PrincipalRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(PrincipalRow);
			}
			public void RemovePrincipalRow(PrincipalRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region PrincipalRow
		[Thinkage.Libraries.Translation.Invariant]
		public class PrincipalRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal PrincipalRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly PrincipalDataTable this_table;
				private readonly PrincipalRow this_row;
				public FAccessor( PrincipalRow this_row )
				{
					this.this_table = ((PrincipalDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the Principal's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.Principal.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the Principal's RoleID column with type link(field Role.Id) with labelkey='Role'
				/// </summary>
				public System.Guid? RoleID {
					get {
							return (System.Guid?)Schema.T.Principal.F.RoleID.EffectiveType.GenericAsNativeType(this_table.F.RoleID[this_row], typeof(System.Guid?));
					}
				}
				/// <summary>
				/// Denotes the Principal's UserID column with type link(field User.Id) with labelkey='User'
				/// </summary>
				public System.Guid? UserID {
					get {
							return (System.Guid?)Schema.T.Principal.F.UserID.EffectiveType.GenericAsNativeType(this_table.F.UserID[this_row], typeof(System.Guid?));
					}
				}
			}
			public RoleRow RoleIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.Role.RowFind<RoleRow>(F.RoleID);
				}
			}

			public UserRow UserIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.User.RowFind<UserRow>(F.UserID);
				}
			}

			public IEnumerable<PermissionRow> GetPermissionPrincipalIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.Permission.OfType<PermissionRow>().Where(r => Schema.T.Principal.F.Id.EffectiveType.GenericEquals(r.F.PrincipalID, F.Id));
			}
			public IEnumerable<RoleRow> GetRolePrincipalIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.Role.OfType<RoleRow>().Where(r => Schema.T.Principal.F.Id.EffectiveType.GenericEquals(r.F.PrincipalID, F.Id));
			}
			public IEnumerable<UserRow> GetUserPrincipalIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.User.OfType<UserRow>().Where(r => Schema.T.Principal.F.Id.EffectiveType.GenericEquals(r.F.PrincipalID, F.Id));
			}
			public IEnumerable<UserRoleRow> GetUserRolePrincipalIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.UserRole.OfType<UserRoleRow>().Where(r => Schema.T.Principal.F.Id.EffectiveType.GenericEquals(r.F.PrincipalID, F.Id));
			}
		}
		#endregion
		#region PrincipalRowChangeEvent
#if PrincipalRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class PrincipalRowChangeEvent : EventArgs {

			private PrincipalRow eventRow;

			private DataRowAction eventAction;

			public PrincipalRowChangeEvent(PrincipalRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public PrincipalRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#region Role
		private bool ShouldSerializeRole() {
			return false;
		}
#if RoleRowChangeEvents
		public delegate void RoleRowChangeEventHandler(object sender, RoleRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class RoleDataTable : DBIDataTable {
			#region Construction
			internal RoleDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal RoleDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(RoleDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.PrincipalID = (DBIDataColumn)t.Columns["PrincipalID"];
				}
				/// <summary>
				/// Denotes the Role's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the Role's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public readonly DBIDataColumn PrincipalID;
			}
			#endregion
			#region EventHandlers
			#if RoleRowChangeEvents
			public event RoleRowChangeEventHandler RoleRowChanged;
			public event RoleRowChangeEventHandler RoleRowChanging;
			public event RoleRowChangeEventHandler RoleRowDeleted;
			public event RoleRowChangeEventHandler RoleRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.RoleRowChanged?.Invoke(this, new RoleRowChangeEvent(((RoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.RoleRowChanging?.Invoke(this, new RoleRowChangeEvent(((RoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.RoleRowDeleted?.Invoke(this, new RoleRowChangeEvent(((RoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.RoleRowDeleting?.Invoke(this, new RoleRowChangeEvent(((RoleRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new RoleDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public RoleRow this[int index] {
				get {
					return ((RoleRow)(this.Rows[index]));
				}
			}
			public void AddRoleRow(RoleRow row) {
				this.Rows.Add(row);
			}
			public RoleRow AddNewRoleRow() {
				return ((RoleRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.Role)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new RoleRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(RoleRow);
			}
			public void RemoveRoleRow(RoleRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region RoleRow
		[Thinkage.Libraries.Translation.Invariant]
		public class RoleRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal RoleRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly RoleDataTable this_table;
				private readonly RoleRow this_row;
				public FAccessor( RoleRow this_row )
				{
					this.this_table = ((RoleDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the Role's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.Role.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the Role's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public System.Guid PrincipalID {
					get {
							return (System.Guid)Schema.T.Role.F.PrincipalID.EffectiveType.GenericAsNativeType(this_table.F.PrincipalID[this_row], typeof(System.Guid));
					}
				}
			}
			public PrincipalRow PrincipalIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.RowFind<PrincipalRow>(F.PrincipalID);
				}
			}

			public IEnumerable<PrincipalRow> GetPrincipalRoleIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.OfType<PrincipalRow>().Where(r => Schema.T.Role.F.Id.EffectiveType.GenericEquals(r.F.RoleID, F.Id));
			}
		}
		#endregion
		#region RoleRowChangeEvent
#if RoleRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class RoleRowChangeEvent : EventArgs {

			private RoleRow eventRow;

			private DataRowAction eventAction;

			public RoleRowChangeEvent(RoleRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public RoleRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#region User
		private bool ShouldSerializeUser() {
			return false;
		}
#if UserRowChangeEvents
		public delegate void UserRowChangeEventHandler(object sender, UserRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class UserDataTable : DBIDataTable {
			#region Construction
			internal UserDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal UserDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(UserDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.PrincipalID = (DBIDataColumn)t.Columns["PrincipalID"];
				  this.AuthenticationCredential = (DBIDataColumn)t.Columns["AuthenticationCredential"];
				  this.Hidden = (DBIDataColumn)t.Columns["Hidden"];
				}
				/// <summary>
				/// Denotes the User's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the User's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public readonly DBIDataColumn PrincipalID;
				/// <summary>
				/// Denotes the User's AuthenticationCredential column with type string(nonnull, minlength 1, maxlength 128, maxlines 0, trim) with labelkey='Authentication Credential'
				/// </summary>
				public readonly DBIDataColumn AuthenticationCredential;
				/// <summary>
				/// Denotes the User's Hidden column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='Hidden'
				/// </summary>
				public readonly DBIDataColumn Hidden;
			}
			#endregion
			#region EventHandlers
			#if UserRowChangeEvents
			public event UserRowChangeEventHandler UserRowChanged;
			public event UserRowChangeEventHandler UserRowChanging;
			public event UserRowChangeEventHandler UserRowDeleted;
			public event UserRowChangeEventHandler UserRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.UserRowChanged?.Invoke(this, new UserRowChangeEvent(((UserRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.UserRowChanging?.Invoke(this, new UserRowChangeEvent(((UserRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.UserRowDeleted?.Invoke(this, new UserRowChangeEvent(((UserRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.UserRowDeleting?.Invoke(this, new UserRowChangeEvent(((UserRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new UserDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public UserRow this[int index] {
				get {
					return ((UserRow)(this.Rows[index]));
				}
			}
			public void AddUserRow(UserRow row) {
				this.Rows.Add(row);
			}
			public UserRow AddNewUserRow() {
				return ((UserRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.User)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new UserRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(UserRow);
			}
			public void RemoveUserRow(UserRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region UserRow
		[Thinkage.Libraries.Translation.Invariant]
		public class UserRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal UserRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly UserDataTable this_table;
				private readonly UserRow this_row;
				public FAccessor( UserRow this_row )
				{
					this.this_table = ((UserDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the User's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.User.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the User's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
				/// </summary>
				public System.Guid PrincipalID {
					get {
							return (System.Guid)Schema.T.User.F.PrincipalID.EffectiveType.GenericAsNativeType(this_table.F.PrincipalID[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the User's AuthenticationCredential column with type string(nonnull, minlength 1, maxlength 128, maxlines 0, trim) with labelkey='Authentication Credential'
				/// </summary>
				public System.String AuthenticationCredential {
					get {
							return (System.String)Schema.T.User.F.AuthenticationCredential.EffectiveType.GenericAsNativeType(this_table.F.AuthenticationCredential[this_row], typeof(System.String));
					}
					set {this_table.F.AuthenticationCredential[this_row] = value; }
				}
				/// <summary>
				/// Denotes the User's Hidden column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='Hidden'
				/// </summary>
				public System.DateTime? Hidden {
					get {
							return (System.DateTime?)Schema.T.User.F.Hidden.EffectiveType.GenericAsNativeType(this_table.F.Hidden[this_row], typeof(System.DateTime?));
					}
					set {this_table.F.Hidden[this_row] = value; }
				}
			}
			public PrincipalRow PrincipalIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.RowFind<PrincipalRow>(F.PrincipalID);
				}
			}

			public IEnumerable<UserRoleRow> GetUserRoleUserIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.UserRole.OfType<UserRoleRow>().Where(r => Schema.T.User.F.Id.EffectiveType.GenericEquals(r.F.UserID, F.Id));
			}
			public IEnumerable<UserPermissionRow> GetUserPermissionUserIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.UserPermission.OfType<UserPermissionRow>().Where(r => Schema.T.User.F.Id.EffectiveType.GenericEquals(r.F.UserID, F.Id));
			}
			public IEnumerable<PrincipalRow> GetPrincipalUserIDChildRows() {
				return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.OfType<PrincipalRow>().Where(r => Schema.T.User.F.Id.EffectiveType.GenericEquals(r.F.UserID, F.Id));
			}
		}
		#endregion
		#region UserRowChangeEvent
#if UserRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class UserRowChangeEvent : EventArgs {

			private UserRow eventRow;

			private DataRowAction eventAction;

			public UserRowChangeEvent(UserRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public UserRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#region UserRole
		private bool ShouldSerializeUserRole() {
			return false;
		}
#if UserRoleRowChangeEvents
		public delegate void UserRoleRowChangeEventHandler(object sender, UserRoleRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class UserRoleDataTable : DBIDataTable {
			#region Construction
			internal UserRoleDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal UserRoleDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(UserRoleDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.PrincipalID = (DBIDataColumn)t.Columns["PrincipalID"];
				  this.UserID = (DBIDataColumn)t.Columns["UserID"];
				}
				/// <summary>
				/// Denotes the UserRole's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the UserRole's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey='Role'
				/// </summary>
				public readonly DBIDataColumn PrincipalID;
				/// <summary>
				/// Denotes the UserRole's UserID column with type link(nonnull, field User.Id) with labelkey='User'
				/// </summary>
				public readonly DBIDataColumn UserID;
			}
			#endregion
			#region EventHandlers
			#if UserRoleRowChangeEvents
			public event UserRoleRowChangeEventHandler UserRoleRowChanged;
			public event UserRoleRowChangeEventHandler UserRoleRowChanging;
			public event UserRoleRowChangeEventHandler UserRoleRowDeleted;
			public event UserRoleRowChangeEventHandler UserRoleRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.UserRoleRowChanged?.Invoke(this, new UserRoleRowChangeEvent(((UserRoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.UserRoleRowChanging?.Invoke(this, new UserRoleRowChangeEvent(((UserRoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.UserRoleRowDeleted?.Invoke(this, new UserRoleRowChangeEvent(((UserRoleRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.UserRoleRowDeleting?.Invoke(this, new UserRoleRowChangeEvent(((UserRoleRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new UserRoleDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public UserRoleRow this[int index] {
				get {
					return ((UserRoleRow)(this.Rows[index]));
				}
			}
			public void AddUserRoleRow(UserRoleRow row) {
				this.Rows.Add(row);
			}
			public UserRoleRow AddNewUserRoleRow() {
				return ((UserRoleRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.UserRole)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new UserRoleRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(UserRoleRow);
			}
			public void RemoveUserRoleRow(UserRoleRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region UserRoleRow
		[Thinkage.Libraries.Translation.Invariant]
		public class UserRoleRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal UserRoleRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly UserRoleDataTable this_table;
				private readonly UserRoleRow this_row;
				public FAccessor( UserRoleRow this_row )
				{
					this.this_table = ((UserRoleDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the UserRole's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.UserRole.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the UserRole's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey='Role'
				/// </summary>
				public System.Guid PrincipalID {
					get {
							return (System.Guid)Schema.T.UserRole.F.PrincipalID.EffectiveType.GenericAsNativeType(this_table.F.PrincipalID[this_row], typeof(System.Guid));
					}
					set {this_table.F.PrincipalID[this_row] = value; }
				}
				/// <summary>
				/// Denotes the UserRole's UserID column with type link(nonnull, field User.Id) with labelkey='User'
				/// </summary>
				public System.Guid UserID {
					get {
							return (System.Guid)Schema.T.UserRole.F.UserID.EffectiveType.GenericAsNativeType(this_table.F.UserID[this_row], typeof(System.Guid));
					}
					set {this_table.F.UserID[this_row] = value; }
				}
			}
			public PrincipalRow PrincipalIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.Principal.RowFind<PrincipalRow>(F.PrincipalID);
				}
			}

			public UserRow UserIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.User.RowFind<UserRow>(F.UserID);
				}
			}

		}
		#endregion
		#region UserRoleRowChangeEvent
#if UserRoleRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class UserRoleRowChangeEvent : EventArgs {

			private UserRoleRow eventRow;

			private DataRowAction eventAction;

			public UserRoleRowChangeEvent(UserRoleRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public UserRoleRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#region UserPermission
		private bool ShouldSerializeUserPermission() {
			return false;
		}
#if UserPermissionRowChangeEvents
		public delegate void UserPermissionRowChangeEventHandler(object sender, UserPermissionRowChangeEvent e);
#endif


		[Thinkage.Libraries.Translation.Invariant]
		public class UserPermissionDataTable : DBIDataTable {
			#region Construction
			internal UserPermissionDataTable(DBI_Table tableSchema, IServer s) :
					base(tableSchema, s) {
				Columns.CollectionChanged += delegate(object sender, System.ComponentModel.CollectionChangeEventArgs ea) {
					_F = null;
				};
			}
#if SerializationSupport
			internal UserPermissionDataTable(DataTable table) :
					base(table.TableName) {
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) {
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
#endif
			#endregion
			#region Typed Column accessor
			internal FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal class FAccessor {
				public FAccessor(UserPermissionDataTable t) {
				  this.Id = (DBIDataColumn)t.Columns["Id"];
				  this.UserID = (DBIDataColumn)t.Columns["UserID"];
				  this.PermissionPathPattern = (DBIDataColumn)t.Columns["PermissionPathPattern"];
				}
				/// <summary>
				/// Denotes the UserPermission's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public readonly DBIDataColumn Id;
				/// <summary>
				/// Denotes the UserPermission's UserID column with type link(nonnull, field User.Id) with labelkey='User'
				/// </summary>
				public readonly DBIDataColumn UserID;
				/// <summary>
				/// Denotes the UserPermission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
				/// </summary>
				public readonly DBIDataColumn PermissionPathPattern;
			}
			#endregion
			#region EventHandlers
			#if UserPermissionRowChangeEvents
			public event UserPermissionRowChangeEventHandler UserPermissionRowChanged;
			public event UserPermissionRowChangeEventHandler UserPermissionRowChanging;
			public event UserPermissionRowChangeEventHandler UserPermissionRowDeleted;
			public event UserPermissionRowChangeEventHandler UserPermissionRowDeleting;

			protected override void OnRowChanged(DataRowChangeEventArgs e) {
				base.OnRowChanged(e);
				this.UserPermissionRowChanged?.Invoke(this, new UserPermissionRowChangeEvent(((UserPermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowChanging(DataRowChangeEventArgs e) {
				base.OnRowChanging(e);
				this.UserPermissionRowChanging?.Invoke(this, new UserPermissionRowChangeEvent(((UserPermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleted(DataRowChangeEventArgs e) {
				base.OnRowDeleted(e);
				this.UserPermissionRowDeleted?.Invoke(this, new UserPermissionRowChangeEvent(((UserPermissionRow)(e.Row)), e.Action));
			}
			protected override void OnRowDeleting(DataRowChangeEventArgs e) {
				base.OnRowDeleting(e);
				this.UserPermissionRowDeleting?.Invoke(this, new UserPermissionRowChangeEvent(((UserPermissionRow)(e.Row)), e.Action));
			}
			#endif
			#endregion
			#region Instantiation used by DataSet.Clone
			// DataSet.Clone calls.CreateInstance on each table in the DataSet being cloned to make the tables for the new DataSet
			protected override DataTable CreateInstance() {
				return new UserPermissionDataTable(Schema, Server);
			}
			#endregion
			#region Row Accessors
			[System.ComponentModel.Browsable(false)]
			public int Count {
				get {
					return this.Rows.Count;
				}
			}
			public UserPermissionRow this[int index] {
				get {
					return ((UserPermissionRow)(this.Rows[index]));
				}
			}
			public void AddUserPermissionRow(UserPermissionRow row) {
				this.Rows.Add(row);
			}
			public UserPermissionRow AddNewUserPermissionRow() {
				return ((UserPermissionRow)(((DBDataSet)this.DataSet).DB.AddNewRowAndBases((DBDataSet)this.DataSet, dsPermission_1_1_4_2.Schema.T.UserPermission)));
			}
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
				return new UserPermissionRow(builder);
			}
			protected override System.Type GetRowType() {
				return typeof(UserPermissionRow);
			}
			public void RemoveUserPermissionRow(UserPermissionRow row) {
				this.Rows.Remove(row);
			}
			#endregion
		}
		#region UserPermissionRow
		[Thinkage.Libraries.Translation.Invariant]
		public class UserPermissionRow : DBIDataRow {
			public FAccessor F {
				get {
					if (_F == null)
						_F = new FAccessor(this);
					return _F;
				}
			}
			private FAccessor _F = null;
			internal UserPermissionRow(DataRowBuilder rb)
				: base(rb) {
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class FAccessor {
				private readonly UserPermissionDataTable this_table;
				private readonly UserPermissionRow this_row;
				public FAccessor( UserPermissionRow this_row )
				{
					this.this_table = ((UserPermissionDataTable)(this_row.Table));
					this.this_row = this_row;
				}
				/// <summary>
				/// Denotes the UserPermission's Id column with type id(nonnull) with labelkey='Id'
				/// </summary>
				public System.Guid Id {
					get {
							return (System.Guid)Schema.T.UserPermission.F.Id.EffectiveType.GenericAsNativeType(this_table.F.Id[this_row], typeof(System.Guid));
					}
				}
				/// <summary>
				/// Denotes the UserPermission's UserID column with type link(nonnull, field User.Id) with labelkey='User'
				/// </summary>
				public System.Guid UserID {
					get {
							return (System.Guid)Schema.T.UserPermission.F.UserID.EffectiveType.GenericAsNativeType(this_table.F.UserID[this_row], typeof(System.Guid));
					}
					set {this_table.F.UserID[this_row] = value; }
				}
				/// <summary>
				/// Denotes the UserPermission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
				/// </summary>
				public System.String PermissionPathPattern {
					get {
							return (System.String)Schema.T.UserPermission.F.PermissionPathPattern.EffectiveType.GenericAsNativeType(this_table.F.PermissionPathPattern[this_row], typeof(System.String));
					}
					set {this_table.F.PermissionPathPattern[this_row] = value; }
				}
			}
			public UserRow UserIDParentRow {
				get {
					return ((dsPermission_1_1_4_2)Table.DataSet).T.User.RowFind<UserRow>(F.UserID);
				}
			}

		}
		#endregion
		#region UserPermissionRowChangeEvent
#if UserPermissionRowChangeEvents
		[Thinkage.Libraries.Translation.Invariant]
		public class UserPermissionRowChangeEvent : EventArgs {

			private UserPermissionRow eventRow;

			private DataRowAction eventAction;

			public UserPermissionRowChangeEvent(UserPermissionRow row, DataRowAction action) {
				this.eventRow = row;
				this.eventAction = action;
			}

			public UserPermissionRow Row {
				get {
					return this.eventRow;
				}
			}

			public DataRowAction Action {
				get {
					return this.eventAction;
				}
			}
		}
#endif
		#endregion
		#endregion
		#endregion

		#region Custom database schema definitions
		#region - the custom Schema class
		/// <summary>
		/// Singleton class containing the schema of all tables,
		/// columns, and relationships in a database.
		/// </summary>
		[Thinkage.Libraries.Translation.Invariant]
		public class SchemaClass : DBI_Database {
			#region singleton construction
			private SchemaClass() {
				_T = new TAccessor(this);
				vstruct = new VAccessor(this);
				__Permission = new DBI_Permission();
				Tables.Add( __Permission);
				__Principal = new DBI_Principal();
				Tables.Add( __Principal);
				__Role = new DBI_Role();
				Tables.Add( __Role);
				__User = new DBI_User();
				Tables.Add( __User);
				__UserRole = new DBI_UserRole();
				Tables.Add( __UserRole);
				__UserPermission = new DBI_UserPermission();
				Tables.Add( __UserPermission);
				CompleteDBI(System.Reflection.Assembly.GetExecutingAssembly(), "manifest://localhost/Thinkage/MainBoss/Database/Upgrade/Schema/dsPermission_1_1_4_2.xafdb", typeof(dsPermission_1_1_4_2));
			 }
			/// <summary>
			/// The instantiation of the singleton SchemaClass object
			/// </summary>
			public static readonly SchemaClass Instance = new SchemaClass();
			#endregion
			#region Custom DBI_Table derivations and their private reference in the schema object
			#region - Permission table
			private DBI_Permission __Permission;

			/// <summary>
			/// Class to describe a Permission table
			/// </summary>
			public class DBI_Permission : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __PrincipalID;
				private DBI_Column __PermissionPathPattern;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_Permission this_table;
					public FAccessor( DBI_Permission this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the Permission's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the Permission's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
					/// </summary>
					public DBI_Column PrincipalID { get { return this_table.__PrincipalID; } }
					/// <summary>
					/// Denotes the Permission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
					/// </summary>
					public DBI_Column PermissionPathPattern { get { return this_table.__PermissionPathPattern; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_Permission()
					: base("Permission", (DBI_Table tableSchema, IServer s) => new PermissionDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 3, "Table 'Permission' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__PrincipalID = Columns["PrincipalID"];
					System.Diagnostics.Debug.Assert(__PrincipalID != null, "Column 'PrincipalID' not found");
					__PermissionPathPattern = Columns["PermissionPathPattern"];
					System.Diagnostics.Debug.Assert(__PermissionPathPattern != null, "Column 'PermissionPathPattern' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#region - Principal table
			private DBI_Principal __Principal;

			/// <summary>
			/// Class to describe a Principal table
			/// </summary>
			public class DBI_Principal : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __RoleID;
				private DBI_Column __UserID;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_Principal this_table;
					public FAccessor( DBI_Principal this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the Principal's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the Principal's RoleID column with type link(field Role.Id) with labelkey='Role'
					/// </summary>
					public DBI_Column RoleID { get { return this_table.__RoleID; } }
					/// <summary>
					/// Denotes the Principal's UserID column with type link(field User.Id) with labelkey='User'
					/// </summary>
					public DBI_Column UserID { get { return this_table.__UserID; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_Principal()
					: base("Principal", (DBI_Table tableSchema, IServer s) => new PrincipalDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 3, "Table 'Principal' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__RoleID = Columns["RoleID"];
					System.Diagnostics.Debug.Assert(__RoleID != null, "Column 'RoleID' not found");
					__UserID = Columns["UserID"];
					System.Diagnostics.Debug.Assert(__UserID != null, "Column 'UserID' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#region - Role table
			private DBI_Role __Role;

			/// <summary>
			/// Class to describe a Role table
			/// </summary>
			public class DBI_Role : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __PrincipalID;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_Role this_table;
					public FAccessor( DBI_Role this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the Role's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the Role's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
					/// </summary>
					public DBI_Column PrincipalID { get { return this_table.__PrincipalID; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_Role()
					: base("Role", (DBI_Table tableSchema, IServer s) => new RoleDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 2, "Table 'Role' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__PrincipalID = Columns["PrincipalID"];
					System.Diagnostics.Debug.Assert(__PrincipalID != null, "Column 'PrincipalID' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#region - User table
			private DBI_User __User;

			/// <summary>
			/// Class to describe a User table
			/// </summary>
			public class DBI_User : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __PrincipalID;
				private DBI_Column __AuthenticationCredential;
				private DBI_Column __Hidden;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_User this_table;
					public FAccessor( DBI_User this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the User's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the User's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey=''
					/// </summary>
					public DBI_Column PrincipalID { get { return this_table.__PrincipalID; } }
					/// <summary>
					/// Denotes the User's AuthenticationCredential column with type string(nonnull, minlength 1, maxlength 128, maxlines 0, trim) with labelkey='Authentication Credential'
					/// </summary>
					public DBI_Column AuthenticationCredential { get { return this_table.__AuthenticationCredential; } }
					/// <summary>
					/// Denotes the User's Hidden column with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) with labelkey='Hidden'
					/// </summary>
					public DBI_Column Hidden { get { return this_table.__Hidden; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_User()
					: base("User", (DBI_Table tableSchema, IServer s) => new UserDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 4, "Table 'User' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__PrincipalID = Columns["PrincipalID"];
					System.Diagnostics.Debug.Assert(__PrincipalID != null, "Column 'PrincipalID' not found");
					__AuthenticationCredential = Columns["AuthenticationCredential"];
					System.Diagnostics.Debug.Assert(__AuthenticationCredential != null, "Column 'AuthenticationCredential' not found");
					__Hidden = Columns["Hidden"];
					System.Diagnostics.Debug.Assert(__Hidden != null, "Column 'Hidden' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#region - UserRole table
			private DBI_UserRole __UserRole;

			/// <summary>
			/// Class to describe a UserRole table
			/// </summary>
			public class DBI_UserRole : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __PrincipalID;
				private DBI_Column __UserID;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_UserRole this_table;
					public FAccessor( DBI_UserRole this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the UserRole's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the UserRole's PrincipalID column with type link(nonnull, field Principal.Id) with labelkey='Role'
					/// </summary>
					public DBI_Column PrincipalID { get { return this_table.__PrincipalID; } }
					/// <summary>
					/// Denotes the UserRole's UserID column with type link(nonnull, field User.Id) with labelkey='User'
					/// </summary>
					public DBI_Column UserID { get { return this_table.__UserID; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_UserRole()
					: base("UserRole", (DBI_Table tableSchema, IServer s) => new UserRoleDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 3, "Table 'UserRole' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__PrincipalID = Columns["PrincipalID"];
					System.Diagnostics.Debug.Assert(__PrincipalID != null, "Column 'PrincipalID' not found");
					__UserID = Columns["UserID"];
					System.Diagnostics.Debug.Assert(__UserID != null, "Column 'UserID' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#region - UserPermission table
			private DBI_UserPermission __UserPermission;

			/// <summary>
			/// Class to describe a UserPermission table
			/// </summary>
			public class DBI_UserPermission : DBIDataDBI_Table {
				public FAccessor F;
				private DBI_Column __Id;
				private DBI_Column __UserID;
				private DBI_Column __PermissionPathPattern;
				[Thinkage.Libraries.Translation.Invariant]
				public struct FAccessor {
					private DBI_UserPermission this_table;
					public FAccessor( DBI_UserPermission this_table )
					{
						this.this_table = this_table;
					}
					/// <summary>
					/// Denotes the UserPermission's Id column with type id(nonnull) with labelkey='Id'
					/// </summary>
					public DBI_Column Id { get { return this_table.__Id; } }
					/// <summary>
					/// Denotes the UserPermission's UserID column with type link(nonnull, field User.Id) with labelkey='User'
					/// </summary>
					public DBI_Column UserID { get { return this_table.__UserID; } }
					/// <summary>
					/// Denotes the UserPermission's PermissionPathPattern column with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) with labelkey='PermissionPathPattern'
					/// </summary>
					public DBI_Column PermissionPathPattern { get { return this_table.__PermissionPathPattern; } }
				}

				/// <summary>
				/// Internal table constructor
				/// </summary>
				internal DBI_UserPermission()
					: base("UserPermission", (DBI_Table tableSchema, IServer s) => new UserPermissionDataTable(tableSchema, s)) {
				}

				/// <summary>
				/// Custom-table-class member variable initialization
				/// </summary>
				public override void SetupVariables() {
					// The columns are predefined by the Xml load. In theory they are in the same order as when this file
					// was built and we could find them by index, but finding them by name is more bullet-proof.
					System.Diagnostics.Debug.Assert(Columns.Count == 3, "Table 'UserPermission' column count mismatch");
					__Id = Columns["Id"];
					System.Diagnostics.Debug.Assert(__Id != null, "Column 'Id' not found");
					__UserID = Columns["UserID"];
					System.Diagnostics.Debug.Assert(__UserID != null, "Column 'UserID' not found");
					__PermissionPathPattern = Columns["PermissionPathPattern"];
					System.Diagnostics.Debug.Assert(__PermissionPathPattern != null, "Column 'PermissionPathPattern' not found");
					F = new FAccessor(this);
				}
			}
			#endregion
			#endregion
			#region T - the public portal for getting the custom-typed DBI_Table objects for each table
			public struct TAccessor {
				private SchemaClass this_schema;
				public TAccessor( SchemaClass this_schema )
				{
					this.this_schema = this_schema;
				}
				#region Accessors
				/// <summary>
				/// Denotes the Permission table with labelkey='Permission'
				/// </summary>
				public DBI_Permission Permission { get { return this_schema.__Permission; }}
				/// <summary>
				/// Denotes the Principal table with labelkey=''
				/// </summary>
				public DBI_Principal Principal { get { return this_schema.__Principal; }}
				/// <summary>
				/// Denotes the Role table with labelkey='Role'
				/// </summary>
				public DBI_Role Role { get { return this_schema.__Role; }}
				/// <summary>
				/// Denotes the User table with labelkey='User'
				/// </summary>
				public DBI_User User { get { return this_schema.__User; }}
				/// <summary>
				/// Denotes the UserRole table with labelkey=''
				/// </summary>
				public DBI_UserRole UserRole { get { return this_schema.__UserRole; }}
				/// <summary>
				/// Denotes the UserPermission table with labelkey=''
				/// </summary>
				public DBI_UserPermission UserPermission { get { return this_schema.__UserPermission; }}
				#endregion
			}
			public TAccessor T { get { return _T; } }
			private TAccessor _T;
			#endregion
			#region V - the public portal for getting the DBI_Variable objects for Database Variables
			public struct VAccessor {
				private SchemaClass this_schema;
				public VAccessor( SchemaClass this_schema )
				{
					this.this_schema = this_schema;
				}
				#region Variable Accessors
				#endregion
			}
			public VAccessor V { get { return vstruct; } }	// Variables
			private VAccessor vstruct;
			#endregion
		}
		#endregion
		#region - The static member that contains the Schema
		public readonly static SchemaClass Schema = SchemaClass.Instance;
		// make a member variable in the class for reference in a dynamic type instance of this object
		public readonly SchemaClass SchemaDynamic = Schema;
		#endregion
		#endregion
		#region Database Path definitions
		[Thinkage.Libraries.Translation.Invariant]
		public class PathClass {
			/// <summary>
			/// Class containing the relationship paths of all tables,
			/// </summary>
			public readonly TAccessor T;
			/// <summary>
			/// Private constructor for singleton creation
			/// </summary>
			private PathClass() {
				T = new TAccessor(this);
			}

			/// <summary>
			/// The instantiation of the singleton Path object
			/// </summary>
			public static readonly PathClass Instance = new PathClass();
			#region DBI_Path Definitions

			#region DBI_Path Permission
			private PathToPermissionRow __pPermission = new PathToPermissionRow( SchemaClass.Instance.T.Permission );

			/// <summary>
			/// The Permission path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToPermissionRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToPrincipalLink _PrincipalID;
				private PathToField _PermissionPathPattern;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToPermissionRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToPermissionRow _BasePath;
					/// <summary>
					/// Provides the path to Permission's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.Permission.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to Permission's PrincipalID with type link(nonnull, field Principal.Id) and labelkey=''
					/// </summary>
					public PathToPrincipalLink PrincipalID { get { if (_BasePath._PrincipalID == null) _BasePath._PrincipalID = new PathToPrincipalLink(_BasePath, Schema.T.Permission.F.PrincipalID ); return _BasePath._PrincipalID; } }
					/// <summary>
					/// Provides the path to Permission's PermissionPathPattern with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) and labelkey='PermissionPathPattern'
					/// </summary>
					public PathToField PermissionPathPattern { get { if (_BasePath._PermissionPathPattern == null) _BasePath._PermissionPathPattern = new PathToField(_BasePath, Schema.T.Permission.F.PermissionPathPattern ); return _BasePath._PermissionPathPattern; } }
				}

				internal PathToPermissionRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToPermissionRow( DBI_Table t ) : base( t ) { }
				internal PathToPermissionRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToPermissionLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToPermissionRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToPermissionRow PathToReferencedRow { get { return (PathToPermissionRow)base.PathToReferencedRow; } }

				internal PathToPermissionLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToPermissionRow(rootTableSchema, columns);
				}
			}
			public class LinkToPermission {
				public LinkToPermission(DBI_Path referencing_path) {
					Id = new PathToPermissionRow(referencing_path.PathThroughLinkage(Schema.T.Permission.F.Id));
				}
				public readonly PathToPermissionRow Id;
			}
			#endregion

			#region DBI_Path Principal
			private PathToPrincipalRow __pPrincipal = new PathToPrincipalRow( SchemaClass.Instance.T.Principal );

			/// <summary>
			/// The Principal path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToPrincipalRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToRoleLink _RoleID;
				private PathToUserLink _UserID;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToPrincipalRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToPrincipalRow _BasePath;
					/// <summary>
					/// Provides the path to Principal's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.Principal.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to Principal's RoleID with type link(field Role.Id) and labelkey='Role'
					/// </summary>
					public PathToRoleLink RoleID { get { if (_BasePath._RoleID == null) _BasePath._RoleID = new PathToRoleLink(_BasePath, Schema.T.Principal.F.RoleID ); return _BasePath._RoleID; } }
					/// <summary>
					/// Provides the path to Principal's UserID with type link(field User.Id) and labelkey='User'
					/// </summary>
					public PathToUserLink UserID { get { if (_BasePath._UserID == null) _BasePath._UserID = new PathToUserLink(_BasePath, Schema.T.Principal.F.UserID ); return _BasePath._UserID; } }
				}

				internal PathToPrincipalRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToPrincipalRow( DBI_Table t ) : base( t ) { }
				internal PathToPrincipalRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToPrincipalLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToPrincipalRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToPrincipalRow PathToReferencedRow { get { return (PathToPrincipalRow)base.PathToReferencedRow; } }

				internal PathToPrincipalLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToPrincipalRow(rootTableSchema, columns);
				}
			}
			public class LinkToPrincipal {
				public LinkToPrincipal(DBI_Path referencing_path) {
					Id = new PathToPrincipalRow(referencing_path.PathThroughLinkage(Schema.T.Principal.F.Id));
				}
				public readonly PathToPrincipalRow Id;
			}
			#endregion

			#region DBI_Path Role
			private PathToRoleRow __pRole = new PathToRoleRow( SchemaClass.Instance.T.Role );

			/// <summary>
			/// The Role path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToRoleRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToPrincipalLink _PrincipalID;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToRoleRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToRoleRow _BasePath;
					/// <summary>
					/// Provides the path to Role's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.Role.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to Role's PrincipalID with type link(nonnull, field Principal.Id) and labelkey=''
					/// </summary>
					public PathToPrincipalLink PrincipalID { get { if (_BasePath._PrincipalID == null) _BasePath._PrincipalID = new PathToPrincipalLink(_BasePath, Schema.T.Role.F.PrincipalID ); return _BasePath._PrincipalID; } }
				}

				internal PathToRoleRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToRoleRow( DBI_Table t ) : base( t ) { }
				internal PathToRoleRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToRoleLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToRoleRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToRoleRow PathToReferencedRow { get { return (PathToRoleRow)base.PathToReferencedRow; } }

				internal PathToRoleLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToRoleRow(rootTableSchema, columns);
				}
			}
			public class LinkToRole {
				public LinkToRole(DBI_Path referencing_path) {
					Id = new PathToRoleRow(referencing_path.PathThroughLinkage(Schema.T.Role.F.Id));
				}
				public readonly PathToRoleRow Id;
			}
			#endregion

			#region DBI_Path User
			private PathToUserRow __pUser = new PathToUserRow( SchemaClass.Instance.T.User );

			/// <summary>
			/// The User path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToPrincipalLink _PrincipalID;
				private PathToField _AuthenticationCredential;
				private PathToField _Hidden;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToUserRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToUserRow _BasePath;
					/// <summary>
					/// Provides the path to User's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.User.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to User's PrincipalID with type link(nonnull, field Principal.Id) and labelkey=''
					/// </summary>
					public PathToPrincipalLink PrincipalID { get { if (_BasePath._PrincipalID == null) _BasePath._PrincipalID = new PathToPrincipalLink(_BasePath, Schema.T.User.F.PrincipalID ); return _BasePath._PrincipalID; } }
					/// <summary>
					/// Provides the path to User's AuthenticationCredential with type string(nonnull, minlength 1, maxlength 128, maxlines 0, trim) and labelkey='Authentication Credential'
					/// </summary>
					public PathToField AuthenticationCredential { get { if (_BasePath._AuthenticationCredential == null) _BasePath._AuthenticationCredential = new PathToField(_BasePath, Schema.T.User.F.AuthenticationCredential ); return _BasePath._AuthenticationCredential; } }
					/// <summary>
					/// Provides the path to User's Hidden with type datetime((min Monday, 01 January 1753 00:00), (max Friday, 31 December 9999 23:59:59.99), divided 100) and labelkey='Hidden'
					/// </summary>
					public PathToField Hidden { get { if (_BasePath._Hidden == null) _BasePath._Hidden = new PathToField(_BasePath, Schema.T.User.F.Hidden ); return _BasePath._Hidden; } }
				}

				internal PathToUserRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToUserRow( DBI_Table t ) : base( t ) { }
				internal PathToUserRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToUserRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToUserRow PathToReferencedRow { get { return (PathToUserRow)base.PathToReferencedRow; } }

				internal PathToUserLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToUserRow(rootTableSchema, columns);
				}
			}
			public class LinkToUser {
				public LinkToUser(DBI_Path referencing_path) {
					Id = new PathToUserRow(referencing_path.PathThroughLinkage(Schema.T.User.F.Id));
				}
				public readonly PathToUserRow Id;
			}
			#endregion

			#region DBI_Path UserRole
			private PathToUserRoleRow __pUserRole = new PathToUserRoleRow( SchemaClass.Instance.T.UserRole );

			/// <summary>
			/// The UserRole path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserRoleRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToPrincipalLink _PrincipalID;
				private PathToUserLink _UserID;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToUserRoleRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToUserRoleRow _BasePath;
					/// <summary>
					/// Provides the path to UserRole's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.UserRole.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to UserRole's PrincipalID with type link(nonnull, field Principal.Id) and labelkey='Role'
					/// </summary>
					public PathToPrincipalLink PrincipalID { get { if (_BasePath._PrincipalID == null) _BasePath._PrincipalID = new PathToPrincipalLink(_BasePath, Schema.T.UserRole.F.PrincipalID ); return _BasePath._PrincipalID; } }
					/// <summary>
					/// Provides the path to UserRole's UserID with type link(nonnull, field User.Id) and labelkey='User'
					/// </summary>
					public PathToUserLink UserID { get { if (_BasePath._UserID == null) _BasePath._UserID = new PathToUserLink(_BasePath, Schema.T.UserRole.F.UserID ); return _BasePath._UserID; } }
				}

				internal PathToUserRoleRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToUserRoleRow( DBI_Table t ) : base( t ) { }
				internal PathToUserRoleRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserRoleLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToUserRoleRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToUserRoleRow PathToReferencedRow { get { return (PathToUserRoleRow)base.PathToReferencedRow; } }

				internal PathToUserRoleLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToUserRoleRow(rootTableSchema, columns);
				}
			}
			public class LinkToUserRole {
				public LinkToUserRole(DBI_Path referencing_path) {
					Id = new PathToUserRoleRow(referencing_path.PathThroughLinkage(Schema.T.UserRole.F.Id));
				}
				public readonly PathToUserRoleRow Id;
			}
			#endregion

			#region DBI_Path UserPermission
			private PathToUserPermissionRow __pUserPermission = new PathToUserPermissionRow( SchemaClass.Instance.T.UserPermission );

			/// <summary>
			/// The UserPermission path information
			/// </summary>
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserPermissionRow : DBI_PathToRow {
				private FAccessor _F;
				public FAccessor F {
					get {
						if (_F == null)
							_F = new FAccessor(this);
						return _F;
					}
				}
				private PathToField _Id;
				private PathToUserLink _UserID;
				private PathToField _PermissionPathPattern;
				[Thinkage.Libraries.Translation.Invariant]
				public class FAccessor {
					public FAccessor( PathToUserPermissionRow basePath ) {
						_BasePath = basePath;
					}
					private readonly PathToUserPermissionRow _BasePath;
					/// <summary>
					/// Provides the path to UserPermission's Id with type id(nonnull) and labelkey='Id'
					/// </summary>
					public PathToField Id { get { if (_BasePath._Id == null) _BasePath._Id = new PathToField(_BasePath, Schema.T.UserPermission.F.Id ); return _BasePath._Id; } }
					/// <summary>
					/// Provides the path to UserPermission's UserID with type link(nonnull, field User.Id) and labelkey='User'
					/// </summary>
					public PathToUserLink UserID { get { if (_BasePath._UserID == null) _BasePath._UserID = new PathToUserLink(_BasePath, Schema.T.UserPermission.F.UserID ); return _BasePath._UserID; } }
					/// <summary>
					/// Provides the path to UserPermission's PermissionPathPattern with type string(nonnull, minlength 1, maxlength 100, maxlines 0, trim) and labelkey='PermissionPathPattern'
					/// </summary>
					public PathToField PermissionPathPattern { get { if (_BasePath._PermissionPathPattern == null) _BasePath._PermissionPathPattern = new PathToField(_BasePath, Schema.T.UserPermission.F.PermissionPathPattern ); return _BasePath._PermissionPathPattern; } }
				}

				internal PathToUserPermissionRow( DBI_Table t, DBI_Column[] cols) : base( t, cols ) { }
				internal PathToUserPermissionRow( DBI_Table t ) : base( t ) { }
				internal PathToUserPermissionRow( DBI_PathToRow p ) : base( p ) { }
			}
			[Thinkage.Libraries.Translation.Invariant]
			public class PathToUserPermissionLink : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				public PathToUserPermissionRow.FAccessor F { get { return PathToReferencedRow.F; } }
				public new PathToUserPermissionRow PathToReferencedRow { get { return (PathToUserPermissionRow)base.PathToReferencedRow; } }

				internal PathToUserPermissionLink( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
				protected override DBI_PathToRow NewPathToRow(DBI_Table rootTableSchema, DBI_Column[] columns) {
					return new PathToUserPermissionRow(rootTableSchema, columns);
				}
			}
			public class LinkToUserPermission {
				public LinkToUserPermission(DBI_Path referencing_path) {
					Id = new PathToUserPermissionRow(referencing_path.PathThroughLinkage(Schema.T.UserPermission.F.Id));
				}
				public readonly PathToUserPermissionRow Id;
			}
			#endregion
			public class PathToField : DBI_Path {
				private LAccessor _L;
				public LAccessor L {
					get {
						if (_L == null)
							_L = new LAccessor(this);
						return _L;
					}
				}
				[System.Obsolete("This field is not a linkage field", true)]
				public new PathToField PathToReferencedRow { get { return null; } }

				internal PathToField( DBI_PathToRow rootPath, DBI_Column c ) : base( rootPath, c ) { }
			}
			#endregion
			public struct TAccessor {
				private PathClass this_path;
				public TAccessor( PathClass this_path )
				{
					this.this_path = this_path;
				}
				#region Accessors
				/// <summary>
				/// Provides the root path for Permission with labelkey='Permission'
				/// </summary>
				public PathToPermissionRow Permission { get { return this_path.__pPermission; } }
				/// <summary>
				/// Provides the root path for Principal with labelkey=''
				/// </summary>
				public PathToPrincipalRow Principal { get { return this_path.__pPrincipal; } }
				/// <summary>
				/// Provides the root path for Role with labelkey='Role'
				/// </summary>
				public PathToRoleRow Role { get { return this_path.__pRole; } }
				/// <summary>
				/// Provides the root path for User with labelkey='User'
				/// </summary>
				public PathToUserRow User { get { return this_path.__pUser; } }
				/// <summary>
				/// Provides the root path for UserRole with labelkey=''
				/// </summary>
				public PathToUserRoleRow UserRole { get { return this_path.__pUserRole; } }
				/// <summary>
				/// Provides the root path for UserPermission with labelkey=''
				/// </summary>
				public PathToUserPermissionRow UserPermission { get { return this_path.__pUserPermission; } }
				#endregion
			}
			public class LAccessorBase {
				protected LAccessorBase(DBI_Path basePath) {
					BasePath = basePath;
				}
				protected readonly DBI_Path BasePath;
				#region Cached Accessor results
				protected PathClass.LinkToPermission _Permission;
				protected PathClass.LinkToPrincipal _Principal;
				protected PathClass.LinkToRole _Role;
				protected PathClass.LinkToUser _User;
				protected PathClass.LinkToUserRole _UserRole;
				protected PathClass.LinkToUserPermission _UserPermission;
				#endregion
			}
			public class LAccessor : LAccessorBase {
				public LAccessor( DBI_Path this_path ) 
					: base(this_path) {
				}
				#region Accessors
				public PathClass.LinkToPermission Permission { get { if (base._Permission == null) base._Permission = new PathClass.LinkToPermission(base.BasePath); return base._Permission; } }
				public PathClass.LinkToPrincipal Principal { get { if (base._Principal == null) base._Principal = new PathClass.LinkToPrincipal(base.BasePath); return base._Principal; } }
				public PathClass.LinkToRole Role { get { if (base._Role == null) base._Role = new PathClass.LinkToRole(base.BasePath); return base._Role; } }
				public PathClass.LinkToUser User { get { if (base._User == null) base._User = new PathClass.LinkToUser(base.BasePath); return base._User; } }
				public PathClass.LinkToUserRole UserRole { get { if (base._UserRole == null) base._UserRole = new PathClass.LinkToUserRole(base.BasePath); return base._UserRole; } }
				public PathClass.LinkToUserPermission UserPermission { get { if (base._UserPermission == null) base._UserPermission = new PathClass.LinkToUserPermission(base.BasePath); return base._UserPermission; } }
				#endregion
			}
		}
		public static readonly PathClass Path = PathClass.Instance;
		#endregion
		#region Label Key Building
		public class LabelKeyBuilder : Thinkage.Libraries.Translation.GeneralKeyBuilder {
			static LabelKeyBuilder Instance = new LabelKeyBuilder();
			private LabelKeyBuilder() {
			}
			protected override Thinkage.Libraries.Translation.ContextReference GetContext() {
				return Thinkage.Libraries.Translation.ContextReference.New("");
			}
			public static Thinkage.Libraries.Translation.Key K([Thinkage.Libraries.Translation.Context("")]string s) {
				return Instance.BuildKey(s);
			}
		}
		#endregion
	}
}
